### ISSUE TITLE
Help with universe annotations

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1042]
I would like to prove the following lemma:
```coq
Require Import Basics.
Require Import Pointed.
Require Import Types.

Local Open Scope path_scope.

Lemma foo `{Univalence} (A : Type)
  : Build_pType (A = A) 1
    = Build_pType (A <~> A) 1%equiv.
Proof.
  apply path_ptype.
  srapply Build_pEquiv.
  - srapply Build_pMap.
    + apply equiv_path.
    + reflexivity.
  - cbn.
    exact (isequiv_equiv_path A A).
Admitted.
```

However I can't get coq to match the last line, so I probably need to be annotating this lemma with universes. I can't quite work out how to do this however.

**Comment by mikeshulman** [comment]
Intriguing!  Here's a simpler case exhibiting the same issue:

```
Require Import Basics.
Require Import Types.

Lemma bar `{Univalence} (A B : Type) : (A = B) = (A <~> B).
Proof.
  apply path_universe_uncurried.
  exact (equiv_equiv_path A B).
Admitted.
```

Perhaps the problem is that when `A` and `B` live in universes `i` and `j`, the type `A <~> B` then lives in universe `max(i,j)`, whereas the type `A = B` lives in some universe `k` that is *strictly* bigger than `i` and `j`; so `(is)equiv_equiv_path` chokes when it tries to equate them.  However, if that's the problem then I don't understand why a goal like `(A = B) = (A <~> B)` typechecks in the first place.  It must be applying some kind of cumulativity to lift `A <~> B` to the same universe as `A = B`, but then why does `(is)equiv_equiv_path` have a problem?  @mattam82 , any ideas?

In the meantime, here's a version that does work:

```
Lemma baz `{Univalence} (A B : Type) : (A = B) = Lift (A <~> B).
Proof.
  apply path_universe_uncurried.
  apply (equiv_compose' (B := A <~> B)).
  - exists lift; exact (isequiv_lift (A <~> B)).
    (* maybe there should be an `equiv_lift`... *)
  - exact (equiv_equiv_path A B).
Defined.
```

**Comment by mikeshulman** [comment]
I tried redefining `Equiv` to land in an arbitrary universe rather than a max:

```
Record Equiv (A:Type@{i}) (B:Type@{j}) : Type@{k} := BuildEquiv {
  equiv_fun : A -> B ;
  equiv_isequiv : IsEquiv equiv_fun
}.
```

but this causes the definition of `lower'_equiv` in `UniverseLevel.v` to fail with `Universe {HoTT.Basics.UniverseLevel.560} is unbound.`.  Is that an Coq bug?  I have no idea what I'm supposed to do with an unbound universe.

**Comment by SkySkimmer** [comment]
unbound universe means there are mode universes than the annotation expected. ie `Definition foo@{} := Type. (* unbound universe *)` but `Definition foo@{i} := Type@{i}.` works

**Comment by mikeshulman** [comment]
Ah, thanks.  I think that error message could be more helpful.  But now I see that's exactly the sort of error I was expecting; changing the number of universes on something basic like `Equiv` would naturally fubar loads of annotations throughout the library (I just wanted to try it to make sure).

**Comment by SkySkimmer** [comment]
> It must be applying some kind of cumulativity to lift A <~> B to the same universe as A = B, but then why does (is)equiv_equiv_path have a problem?

Cumulativity between universes is automatic, but between types it's not without using `Cumulative` when declaring the relevant inductives (eg `Equiv@{i j} A B` to `Equiv@{i' j'} A B`).

If we make `IsEquiv` and `Equiv` universe-cumulative  both the original and reduced cases work.

I noticed that `isequiv_path` has type (with annotations) `forall (A:Type@{a}) (B:Type@{b}) (p:@paths@{x} Type@{ab} A B), @IsEquiv@{a ab} A B (transport (fun X:Type@{ab} => X) p)` (ab is morally the max of a and b, x is its successor)
If we try to make it more symmetric using `IsEquiv@{a b}` and without universe-cumulative `IsEquiv` we get `a=b=ab`.
I think this is related in some way, but not sure if it's the actual reason.

**Comment by Alizter** [comment]
@mikeshulman I used Lift as you said, which works but now I can't really use the lemma. It just seems to push the universe problem down the line. (Either that or bar needs to be modified as well but that is not so obvious to me).

Sticking a Lift around `A <~> A` in bar however makes the final `exact _.` fail.

```
Require Import Basics.
Require Import Pointed.
Require Import Types.

Local Open Scope path_scope.

Local Notation "( X , x )" := (Build_pType X x).

Lemma foo `{Univalence} (A : Type)
  : (A = A, 1) = (Lift (A <~> A), 1%equiv).
Proof.
  apply path_ptype.
  serapply (pequiv_compose (B := (A <~> A, 1%equiv))).
  { srapply Build_pEquiv.
    + srapply Build_pMap.
      - apply equiv_path.
      - reflexivity.
    + apply isequiv_equiv_path. }
  srapply Build_pEquiv.
  + srapply Build_pMap.
    - apply lift.
    - reflexivity.
  + apply isequiv_lift.
Defined.

Lemma bar `{Univalence} (A : Type)
  : Build_pType (A <~> A) 1%equiv
  = Build_pType {f : A -> A & IsEquiv f} (idmap; isequiv_idmap A).
Proof.
  apply path_ptype.
  apply pequiv_inverse.
  srapply Build_pEquiv.
  + srapply Build_pMap.
    - apply issig_equiv.
    - reflexivity.
  + exact _.
Defined.

Context {A : Type}.
Check (foo A @ bar A).
```

**Comment by mikeshulman** [comment]
Sorry, I don't understand what it means for a non-universe type to "be cumulative"?  And why it matters here?

**Comment by mikeshulman** [comment]
@Alizter what are you using this lemma for?

**Comment by Alizter** [comment]
@mikeshulman I am trying to prove the local-global looping lemma in [Kraus-Sattler](https://arxiv.org/abs/1311.4002). Here is [my work](https://github.com/Alizter/HoTT/blob/imaginaroid/contrib/PointedFamily.v).

**Comment by SkySkimmer** [comment]
>Sorry, I don't understand what it means for a non-universe type to "be cumulative"? And why it matters here?

https://coq.inria.fr/distrib/current/refman/addendum/universe-polymorphism.html#cumulative-noncumulative

**Comment by mikeshulman** [comment]
@SkySkimmer thanks for the thought, but I'm hoping for an actual explanation of what cumulativity *means*.  There are a few indications in that reference manual page of what it might mean, but overall it seems to assume that the reader knows what it means, and just explains how to indicate cumulativity with commands.

**Comment by mattam82** [comment]
In short, cumulative inductive types extend the cumulativity relation from arities (`forall G, Type@{i} <= forall G, Type@{j}`) to applied inductive types: `Ind@{i} A <= Ind@{j} B`  becomes derivable under certain variance conditions (which can be seen by `*,=,+` annotations on the universe binders for `Ind`). This avoids the use of lifts to show e.g. that `list@{i} nat = list@{Set} nat` definitionally for any well-typed `list@{i} nat` application and embodies the fact that in many cases universe annotations are definitionally irrelevant. This is justified by a set-theoretic model, where the two `list@{_} nat` instances are actually interpreted as the same set.

**Comment by mikeshulman** [comment]
So a "cumulative inductive type" is, roughly, one that is preserved definitionally by the implicit lift from one universe to a larger one?  That seems a very confusing name, since ordinarily we talk about the *universes* being cumulative; in "cumulative inductive type" the adjective "cumulative" means rather the opposite, we should say something like "cumulativity-respecting inductive type".

Now I think I understand the problem.  The `Equiv` instance expected by `path_universe_uncurried` is applied to two types in the same universe (because they also have to be related by an `=`), so although the `A <~> B` appearing as its argument must be lifted to a higher universe to match the `A = B` in its other argument.  But the `Equiv` instance produced by `equiv_equiv_path` compares an equality type `A = B` in a larger universe to an equivalence type `A <~> B` in the smaller universe.  So these two outer `Equiv` instances are applied at different universe levels, and we need `Equiv` to be cumulativity-respecting in order to identify them.

I have to say all of this is making me more sympathetic to the point of view that one should dispense with cumulativity entirely...

**Comment by Alizter** [comment]
It is all working now, thanks for the fix! I can go back to being ignorant about universes again :-)

**Comment by spitters** [comment]
@mikeshulman About cumulativity. Jon seems to have a nice [algebraic treatment](http://www.jonmsterling.com/pdfs/algebraic-universes.pdf).
I haven't read it in detail, but it does show that there is a good theory of cumulative universes.
