### ISSUE TITLE
Why is trunc_equiv opaque?

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1091]
In `Trunc.v` there is a definition `trunc_equiv`:

```coq
(** Equivalence preserves truncation (this is, of course, trivial with univalence).
   This is not an [Instance] because it causes infinite loops.
   *)
Definition trunc_equiv A {B} (f : A -> B)
  `{IsTrunc n A} `{IsEquiv A B f}
  : IsTrunc n B.
Proof.
  generalize dependent B; generalize dependent A.
  simple_induction n n IH; simpl; intros A ? B f ?.
  - exact (contr_equiv _ f).
  - intros x y.
    exact (IH (f^-1 x = f^-1 y) (H (f^-1 x) (f^-1 y)) (x = y) ((ap (f^-1))^-1) _).
Qed.
```
Now this breaks my computation. Therefore I swapped `Qed` for `Defined`. The whole library compiles, apart from `Card.v` which gets stuck (and memory gets out of hand).

Specifically in Fibrations.v, we have the following definition:
```coq
Global Instance isequiv_ap_isembedding {A B} (f : A -> B) `{!IsEmbedding f}
  : forall x y, IsEquiv (@ap _ _ f x y).
Proof.
  intros x y. apply isequiv_fcontr,_.
Defined.
```
This uses trunc_equiv in some critical way. It then becomes a bit useless that such an equivalence exists since the inverse doesn't compute.

My questions are as follows:

 * Can we have a better computationally behaved version of `isequiv_ap_isembedding`?
 * Why is `trunc_equiv` so critical to memory usage in `Card.v`?

**Comment by jdchristensen** [comment]
There's a related problem that is `eisadj_other` in Equivalences.v (formerly `other_adj`) is made transparent, then coq spins while checking Card.v. The problem is in the call to `strip_truncations` in the `reduce` tactic during the proof of `exp_zero_card`.  If we can fix this, then we can inline the proof of `eisadj_other` into `isequiv_inverse`, and use `eisadj (f^-1)` in place of `eisadj_other`.
