### ISSUE TITLE
"make" does (almost) nothing, after modifications and even after "make clean" 

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#111]
`make` intermittently fails to detect when it should be (re)compiling files after modifications.  Usually `make clean` successfully resets this, but sometimes even this doesn’t help: it re-runs `coqdep`, but not `hoqc`.

I’ve had this happen on multiple occasions, but have no idea how to reproduce it, I’m afraid. Have others had the same problem?

[Sample terminal session output.] (https://gist.github.com/peterlefanulumsdaine/227c628cddb626e0d506)

I’m running Mac OS 10.6.8; can provide further system details if anyone has ideas what might be relevant.

**Comment by JasonGross** [comment]
Our makefile has changed enough since this that I will assume it no longer happens.

I will note that the primary cause, nowadays, of `make` not doing the right thing, is that if we use non-absolute imports, after moving files around, Coq will often find the old .vo file rather than the new .v file, and use the old version improperly.  (I don't know of any way to fix this other than by using absolute imports everywhere.)
