### ISSUE TITLE
Install instructions for windows

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1172]
I'm creating this issue as a small how-to guide on installing the library from scratch on windows. We should at some point merge this the install instructions.

1. Install the [precompiled binaries for coq](https://github.com/coq/coq/releases). Just pick the one labelled latest release and run the exe file.
2. Run the [cygwin installer](https://cygwin.com/install.html). It doesn't matter which version, 64 and 32 both work.
3. When you are told to choose packages, select the following packages (use the search bar)
  `git`, `make`, `ocaml`, `automake`, `libtool`
You can select these packages by choosing a version from the drop down in the installer.
4. Complete the installation of cygwin.
5. Run cygwin and check that git works by running `git`. It should just give you the help screen.
6. Run `git clone https://github.com/HoTT/HoTT` to clone the HoTT library, or change this to your fork if you wish to push to your own fork later.
7. Once that has finished downloading, change directory into the HoTT folder `cd HoTT`.
8. Run `./autogen.sh`
9. Configure the library by running `./configure COQBIN="/cygdrive/c/Coq/bin/"`. This tells the HoTT library where to find the coq binaries. This is of course assuming the coq binaries were installed in `C:\Coq\bin`. When in cygwin you can access your C drive through `/cygdrive/c`.
10. Run `make`. This will take some time.
11. You should now be able to run hoqide and hoqc. To try it out run `./hoqide &` in your HoTT directory. The ampersand will let the process run in the background so you can continue to use the terminal.
12. If all has gone well you will have coqide running with the HoTT library. Type `Require Import Basics.` and get coqide to check it to really make sure.

**Comment by mikeshulman** [comment]
Sounds great!  I assume you've checked this and it works on at least one Windows system.  Why bother with the issue, just put it directly into INSTALL.md.

**Comment by Alizter** [comment]
@mikeshulman I've checked this myself on a Window machine. I have pinned this issue so it is easily visible. I will add this to INSTALL.md once I know this works for others next week.

**Comment by mikeshulman** [comment]
Are we ready to put this in `INSTALL.md` now?

**Comment by spitters** [comment]
@MSoegtropIMC Is the expert on installing windows, and has provided an installer before.

**Comment by MSoegtropIMC** [comment]
Until we have something better, the instructions looks good. I would have added HoTT already to the usual Windows installer. The issue last time I tried was that the default install locations of the HoTT library mess up non HoTT usages of Coq. But the fix to this should not be more complicated than configuring HoTT so that it installs the libraries in a place Coq wouldn't look at unless explicitly told to do so. Maybe this is even fixed meanwhile.

**Comment by artagnon** [comment]
On Windows, is the `hoqtop` shim in $PATH, so that people can use HoTT from
Emacs seamlessly?

Do you happen to know which libraries conflict on the Windows installation?

**Comment by MSoegtropIMC** [comment]
> Do you happen to know which libraries conflict on the Windows installation?

I would say everything which has the same name as a Coq standard library and is not the same thing must be installed outside of the default Coq search path. I would suggest to create a new top level lib folder (say lib/coqhott) and put the HoTT stuff there. But I must admit I know close to nothing about HoTT in Coq and can't really tell. One needs to experiment. If someone can come up with a tested folder structure so that normal Coq and HottCoq work seamlessly together, this would definitely speed up the process of having HoTT in the standard Coq Windows installer.

> On Windows, is the `hoqtop` shim in $PATH, so that people can use HoTT from
Emacs seamlessly?

The Coq Windows installer does not mess with the %PATH% or any other environment variable in any way. If you need this, it is easy to do manually, either permanently or start emacs from a shim.

**Comment by Alizter** [comment]
OK so I've created a PR and copied these instructions into a page on the wiki, we can close this issue when #1189 gets merged.

**Comment by KyleDavidE** [comment]
I have found a lot of success using running this within Windows Subsystem for linux, using VSCoq / the vscode remote extension for the editing interface.

It may be worth noting that this is an option with possibly fewer headaches.

(you do need to manually setup a _CoqProject though, I could not get vscode to use the hoqtop executables)

**Comment by artagnon** [comment]
> I could not get vscode to use the hoqtop executables

See https://github.com/coq-community/vscoq/pull/97.
