### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#1221]
It seems to be sporadically (?) unable to find `libgraphviz4`?

**Comment by JasonGross** [comment]
Travis is currently having issues with connecting to launchpad during apt-get update.  (My guess is that the package hoating sites rate-limit or see Travis as a DOS attack or something.)  Maybe we should use something like https://github.com/mit-plv/fiat-crypto/blob/master/etc/ci/sudo-apt-get-update.sh to make it clear when this is the issue with Travis.  This has happened maybe half a dozen times before, and they usually manage to fix the problem after a couple of weeks or months.  At this point I'm pretty cynical about reporting this issue to Travis, since the past *n* times haven't resulted in lasting fixes.  (Feel free to find or link to the relevant bug report on Travis though.)

**Comment by Alizter** [comment]
It might be a good time to bring up that Travis isn't the only CI we have to use. Recently we have Github actions which seems to satisfy all our needs. I wouldn't mind working out how to set it up.
See: [https://knapsackpro.com/ci_comparisons/github-actions/vs/travis-ci](https://knapsackpro.com/ci_comparisons/github-actions/vs/travis-ci f) for a comparison with travis.

**Comment by JasonGross** [comment]
Switching to GitHub Actions seems like a good idea, as long as we can get it to run on PRs.  I don't have time to look into it much right now, but if you figure out how to make it work, I'm happy to review and approve
