### ISSUE TITLE
Inverse of equiv_o_to_O

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/HoTT#1233]
`equiv_o_to_O` is the equivalence sending `g : O P -> Q` to `g o (to O P) : P -> Q` when `Q` is `O`-local.  It is shown to be an equivalence like this:
```
Global Instance isequiv_o_to_O `{Funext}
       (O : ReflectiveSubuniverse) (P Q : Type) `{In O Q}
: IsEquiv (fun g : O P -> Q => g o to O P)
:= isequiv_ooextendable _ _ (extendable_to_O O).
```
By `O_rec_beta`, we know that `O_rec`, which sends `f : P -> Q` to a map `O P -> Q`, is a one-sided inverse for `equiv_o_to_O`, and therefore is a two-sided inverse.  However, unless I'm confused, the proof above picks a different inverse.  It's easy enough to fix this by replacing the above with
```
Global Instance isequiv_o_to_O `{Funext}
       (O : ReflectiveSubuniverse) (P Q : Type) `{In O Q}
  : IsEquiv (fun g : O P -> Q => g o to O P).
Proof.
  srapply isequiv_adjointify.
  - apply O_rec.
  - intro f.
    funext p.
    apply O_rec_beta.
  - intro g.
    apply path_forall.
    apply O_indpaths.
    rapply O_rec_beta.
Defined.
```
but what I'm wondering is whether the proof of `isequiv_ooextendable` could instead be adapted to choose this more obvious inverse.

**Comment by mikeshulman** [comment]
Probably.  I expect the thing to do would be to redefine `isequiv_extendable` explicitly rather than by going through "pathsplit".  It wouldn't then be definitionally equal to the underlying function of `equiv_extendable_isequiv`, unless we also redefined the latter, but that's probably not important.

**Comment by jdchristensen** [comment]
I don't understand what this all means, but by doing fairly naive substitutions I came up with:
```
  Definition isequiv_extendable `{Funext} (n : nat)
             {A B : Type} {C : B -> Type} {f : A -> B}
             (E : ExtendableAlong n.+2 f C)
    : IsEquiv (fun g : forall b, C b => g oD f).
  Proof.
    srapply isequiv_adjointify.
    - intro h. apply (fst E h).1.
    - intro h.
      funext p.
      apply ((fst E h).2 p).
    - intro g.
      apply path_forall.
      refine (fst (snd E _ g) _).1.
      rapply ((fst E _).2).
  Defined.
```
It's too bad that it's so much longer and more cryptic than what was there before.

I'm surprised that the short proof doesn't produce the natural inverse.  It's hard to think of what other inverse it would choose.  Is there a chance that a small change deeper in these proofs could make this work?  The inverse that gets chosen sends `g` to `(fst (extendable_to_O O 2) g).1` instead of `(fst (extendable_to_O O 1) g).1`.

**Comment by mikeshulman** [comment]
Ah, I see.  The reason this is possible is because of the "poor man's coinduction" used to define `ooExtendableAlong`.  An element of `ooExtendableAlong` consists of -- unrelated! -- elements of `ExtendableAlong n` for all `n`, and an element of `ExtendableAlong n` contains elements of `ExtendableAlong k` for all k<n.  So an element of `ooExtendableAlong` actually contains infinitely many different elements of `ExtendableAlong 1`, one inside of the element of `ExtendableAlong n` for each n>0.  The obvious way to get an element of `ExtendableAlong 1` is to look at the case n=1, but to get to pathsplit we need an element of `ExtendableAlong 2`, so the current proofs just take the case n=2.

Which makes me think that in fact, modifying `isequiv_extendable` isn't going to work.  Did you try your suggested version and see whether it actually solves the problem?  Now I think the way to solve it would be
```
  Definition isequiv_ooextendable `{Funext}
             {A B : Type} (C : B -> Type) (f : A -> B)
  : ooExtendableAlong f C -> IsEquiv (fun g => g oD f)
    := fun ps => isequiv_extendable 0 (fst (ps 1%nat), snd (ps 2)).
```

**Comment by jdchristensen** [comment]
Ah, I see.  You are right that my method didn't fix the problem, and your method does.  Want me to make a PR?
