### ISSUE TITLE
Reserve DPath/Cubical notations in Basics/Notations.v

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#1265]
that.

**Comment by Alizter** [comment]
So reserving the notations "@h" and "@v" from PathSquare in Basics/Notations.v causes @h to be wrongly parsed in files such as theories/HProp.v. This was an issue I highlighted in #1173. I am thinking of solving this by ditching the @h and @v notations. The one for cubes is less threatening since @lr is a pretty rare thing to write.

**Comment by mikeshulman** [comment]
Yes, that's definitely a problem with the notations that should be fixed.  I still like my suggestion of `@@h`.
