### ISSUE TITLE
What is the role of `contrib/old`?  Keeping old code present but not in makefile seems bad.

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#1338]
I have an external development based over the HoTT library, which uses the lemma `einv_V` from `EquivGroupoids.v`, which got moved to `contrib/old` in #1287/#1288.  The motivation given there is that `EquivGroupoids.v` wasn’t used by anything else in the library, and should be deprecated for internal use, because it depends on `Funext` more than is desirable.

This is rather disruptive to external developments (more so than most moves/changes within the library), since files in `contrib/old` are not built by `make`, and so there’s now no clean way to import them.

**Generally, it feels like having `contrib/old` around but not in the makefile is a mistake.**  Files there aren’t importable, and will go stale, so are essentially no better off than deleted files (which are always still accessible in repo history anyway) — but moving files to `contrib/old` *feels* much less drastic than deleting them, and so gets done with less compunction.

**Am I missing something here — are there any advantages to keeping files around in `contrib/old` rather than deleting them?**  (On a quick search, I can’t find any previous discussion of this point.)

Assuming people agree that keeping non-maintained code around is bad, I propose:

- for the files in `contrib/old` that haven’t staled too much and seem potentially still of interest: bring them up to date and add them to `_CoqProject`

- for files that have staled too much to be easily resurrected, or that seem very clearly bad/obsolete: delete them entirely (and anyone who wants can still resurrect them from repo history later)

**Comment by mikeshulman** [comment]
i'm not sure why this directory exists, and I certainly wasn't aware it had so much in it!  Clearly the right thing to do when we remove something from the library is to just delete it; that's what git history is for.  I haven't looked at all those files, but I assume the right thing to do would be to delete them.  But anyone who wants to keep some particular one is welcome to raise a discussion about that -- do you think we should keep EquivGroupoids?

**Comment by Alizter** [comment]
I agree that we should remove contrib/old entirely since we have git history.

I think in the future if we delete files, we should at least mention what the good alternatives to those lemmas are. In this case `EquivGroupoids.v` is just various lemmas in `Basics/Equivalences.v` wrapped up with `path_equiv`. However I couldn't find the non-funext version of `einv_V`! So I think we should add it to the library.

**Comment by Alizter** [comment]
Here is a checklist of the files:
- [ ] ├── Conjugation.v
- [ ] ├── EquivGroupoids.v
- [ ] ├── ExtensionalityAxiom.v
- [ ] ├── FiberEquivalences.v
- [ ] ├── FiberSequences.v
- [ ] ├── Freudenthal.v
- [ ] ├── FunextEquivalences.v
- [ ] ├── Funext.v
- [ ] ├── HIT
- [ ] │   ├── Circle.v
- [ ] │   ├── CircleWellDefined.v
- [ ] │   ├── ImpredicativeInterval.v
- [ ] │   ├── Integers.v
- [ ] │   ├── IsInhab.v
- [ ] │   ├── Makefile
- [ ] │   ├── Pi1S1.v
- [ ] │   └── README.txt
- [ ] ├── Homotopy.v
- [ ] ├── Paths.v
- [ ] ├── UnivalenceAxiom.v
- [ ] ├── Univalence.v
- [ ] └── UsefulEquivalences.v

We can discuss each file and what we want to keep from it.

**Comment by Alizter** [comment]
Starting with `EquivGroupoids.v`: I believe we want to have a non-funext version of `einv_V`. Is there anything else?

**Comment by Alizter** [comment]
I've created a draft PR here: https://github.com/HoTT/HoTT/pull/1339

You can push directly to this PR.

**Comment by Alizter** [comment]
Actually I've just noticed that the lemma `einv_V` is just reflexivity. Perhaps instead of rewriting it you use the `change` tactic? This converts along definitional equality in coq.

You can even be more specific and do something like `change f with (f^-1)^-1`.

**Comment by Alizter** [comment]
So I think instead of adding a lemma like einv_V we just add a "top tip" on using `change`?

**Comment by peterlefanulumsdaine** [comment]
“Top tips” are much less useful than lemmas, because they’re not discoverable when needed. With any moderately-large library, people don’t find lemmas by reading through the files, and even when they do read files, they won’t remember every little lemma/tip like this.  Having something that’s discoverable via `Search`, `SearchAbout` etc. is definitely added value.

As such, I do think `EquivGroupoid` is useful — even the ones that are just `equiv_path` wrappers around reflexivity or lemmas from `Basics.Equivalences` — and I vote for keeping it.

**Comment by peterlefanulumsdaine** [comment]
Thanks for starting the draft pull request — I was intending to, but you beat me to it :-)

How is the checklist of files to be used?  Does checking a box mean “keep this file”, “discard this file”, or “this file has been discussed and a decision made”?  I guess “discard by default, check boxes for any we want to keep”?

**Comment by Alizter** [comment]
All the files in the checklist are intended to be deleted, but we need to discuss if we want to keep anything first.

**Comment by mikeshulman** [comment]
If we do want to keep the lemmas in EquivGroupoids, then maybe it would be better to move them into Basics/Equivalences?

**Comment by mikeshulman** [comment]
It would be nice if we had a consistent and brief naming scheme for two lemmas that differ only in whether they assert a path of functions or a homotopy.

**Comment by peterlefanulumsdaine** [comment]
> All the files in the checklist are intended to be deleted, but we need to discuss if we want to keep anything first.

But just to be clear: what is checking the box by a file meant to mean?  “Keep”, “delete”, or “this has been discussed”?

> It would be nice if we had a consistent and brief naming scheme for two lemmas that differ only in whether they assert a path of functions or a homotopy.

Also (in this case) the lemmas denote an equality of *equivalences*, not of underlying functions, just to add an extra layer.  I suggest though that to avoid getting bogged down, in this PR we just reinstate the file `EquivGroupoids` somewhere (either its original location, or `contrib/deprecated`, or wherever else anyone prefers) and then start a separate issue afterwards about whether/how to rename its lemmas and fold them into `Basics/Equivalences`?

Just to illustrate the usefulness of these lemmas (to show why I’m arguing for keeping them despite these naming headaches): in my use-case, I want to replace an equivalence `long_expression` several layers deep inside a goal type with `(long_expression^-1)^-1`.  Currently I can do this just with `rewrite <- einv_V`, or various other one-liner ways of invoking `einv_V`.  Without `einv_V`, the two best alternatives I’ve been able to find are either something like:
```
  [drill down to the equivalence using `ap`, etc]
  apply path_equiv.
  change long_expression with ((long_expression^-1)^-1)%equiv.
  apply idpath. 
```
or else just an `assert (((long_expression^-1)^-1)%equiv = long_expression`, re-proving this specific case of `einv_V`, and then rewriting with it.  Both of these are harder to read, write, and discover than just having the lemma proved once and discoverable/reusable thereafter.

**Comment by Alizter** [comment]
I'm intending to delete the whole of contrib/old but there are lemmas in various files that we might want to keep. I don't think we should keep any of the files themselves.

**Comment by Alizter** [comment]
You shouldn't need to drill down into the equivalence. The `change` tactic would find all instances of `long_expression` in the goal and change them to the definitionally equal form `((long_expression^-1)^-1)`. The justification for doing this is that they both noramalize in coq to the same term (i.e. they are definitionally equal).

**Comment by peterlefanulumsdaine** [comment]
@Alizter Unless I’m missing something, the underlying functions are judgementally equal, but as *equivalences*, `long_expression` and `((long_expression^-1)^-1)` are not judgementally equal.  (For instance, `reflexivity` doesn’t work as a proof for `einv_V`.)  Besides that, the `change` tactic is often quite fiddly to apply, for various reasons; equality lemmas are often much easier to use.

Regarding “I don't think we should keep any of the files themselves.”: why do you want to delete this file?  On the one hand, I can keep arguing why I’d like to keep `EquivGroupoids`.  But on the other hand, for good-quality material in the library which some people find useful, surely the burden of proof should be on the proposal to delete it, not on the plea to keep it?

**Comment by mikeshulman** [comment]
I think what Ali was saying is what I was also saying, that it's fine if we want to keep the *contents* of EquivGroupoids but we should put it somewhere else (e.g. in Basics/Equivalences).  Peter, do you think specifically that these lemmas should stay in a file called theories/EquivGroupoids?

**Comment by Alizter** [comment]
@peterlefanulumsdaine You're right, I didn't fully take in what you were saying before. Regarding the fact that you have to specify all the ap's etc, @jdchristensen made a rewrite-like tactic that does this for you. You would use it similarly to how you use rewrite, but via some clever tactics it constructs a nice proof term. It might be something that is helpful.

Regarding the file, I don't think we should keep EquivGroupoids since it is a bit confusing for users. Previously, results about equivalences were scattered throughout the library. Recently we have cleaned it up a bit to two main files. The file in Basics and the file in Types. If we add EquivGroupoids back in there will be yet another place to find equivalence lemmas which can be confusing.

Therefore, what I am suggesting is that we pull out the important lemmas from EquivGroupoids and stick them in Types/Equiv.v. However, if you have a good reason to want to keep EquivGroupoids as a file I am open to doing that as well.

**Comment by mikeshulman** [comment]
Hrm, I suppose you're right, the ones that use `path_equiv` can't be in `Basics`.  But `Types/Equiv` seems reasonable too.

**Comment by Alizter** [comment]
OK, I'll give a detailed rundown of which files I think should be removed and which should have their contents extracted before removal.

* Conjugation

This is the initial file I removed to get the PR rolling. The comment reads:
```
(** Conjugation operation that was put into [Paths] by Assia and Cyril.
   It is useful in group theory, but it is not so clear what it is for
   in HoTT. So we store it away here, in case someone needs it later. *)
```
I don't think it is worth keeping any of these lemmas. We use similar operations when showing loops is a functor for example, and we seem to get on fine without these.

* ExtensionalityAxiom.v

We should remove this.

* FiberEquivalences.v

The "fundamental theorem of homotopy type theory" as Egbert would say. 4.7.7 in the book and `@HoTT.Types.Equiv.equiv_total_iff_equiv_fiberwise` in the library. We should therefore delete this file.

* FiberSequences.v

This can be found in HFiber.v. I say we delete this.

* Homotopy.v

This is just an indexing file, we should remove it.

* Freudenthal.v

Subsumed by theories/Homotopy/BlakersMassey.v

* Paths.v

This contains various path lemmas, most of which we have. There are also quite a few tactics for manipulating paths. I don't think that these need to be used any longer since standard tactics work well enough. I believe these were originally introduced to get around coq unification issues, but this doesn't seem to relevant any longer 

* UnivalenceAxiom.v
* Univalence.v

Just the statement of the univalence axiom and some tactics to work with the redexes. There is also equivalence induction which we already have. We should remove these.

* UsefulEquivalences.v

Most of these lemmas are scattered throughout `Types`. We should delete this.

Now going into the HIT folder:

* Circle.v
* CircleWellDefined.v

This is an old hacky way to get circles in coq. I am not sure anything here is relevant anymore. We should delete these.

* ImpredicativeInterval.v

Not sure this is useful. We have Interval.v in theories/HIT which proves funext in Metatheory/IntervalImpliesFunext.v . I say we delete.

* Integers.v

A definition of integers for Pi1S1.v. We should remove this.

* IsInhab.v

Propositional truncation. Most of this can be found in Modalities or Truncations. We should delete it.

---

That leaves us with the following files to discuss further:

* EquivGroupoids.v

Currently in discussion.

* Funext.v

As far as I can see, most of this is asserting the various different funext axioms and proving properties about them. I believe most of this is covered by theories/Metatheory. However there are things about AC which I am not sure we have in the main library. Perhaps we should discuss this further.

* FunextEquivalences.v

There are various equivalences that I don't believe we have explicitly in the library. I'm not sure if they will be useful, but we should discuss this.

* Pi1S1.v

We don't have this proof in the library. Is it worth keeping around?

**Comment by peterlefanulumsdaine** [comment]
> Therefore, what I am suggesting is that we pull out the important lemmas from EquivGroupoids and stick them in Types/Equiv.v. However, if you have a good reason to want to keep EquivGroupoids as a file I am open to doing that as well.

I don’t particularly care that the material of `EquivGroupoid` stays in a single file — I’m very happy for its lemmas to be reorganised into better locations.  What I’m asking is: can we resurrect *all* the material of `EquivGroupoid`, not the specific few lemmas that happened to spark this discussion?  I find such lemmas very useful to have around; if they’re deleted, I’m likely to end up rewriting some of them in my own developments in future, which isn’t dreadfully onerous but is just unnecessary duplication of effort when the lemmas have already been written here.

And I suggest factoring the process as “resurrect `EquivGroupoid` in this PR, and reorganise it in a second issue/PR”, just so that this PR doesn’t get bogged down in the discussion of how to do the reorganisation?  Indeed, it could make sense for the whole thing to be factored further as “delete all of `contrib/old`” / “resurrect `EquivGroupoid`” / “reorganise the material of `EquivGroupoid`”.

Regarding the other files: I think it makes sense for them all to be deleted now in this PR (since it’s really just changing them from pseudo-deleted to deleted), and then raise separate issues afterwards for files that anyone wants to resurrect.  What I meant by my remark about the burden of proof being on the deleter was that *if* someone asks to resurrect material that was deleted without a strong reason, they shouldn’t need to justify the resurrection so much.

**Comment by Alizter** [comment]
OK, I've gone ahead and deleted the files I indicated. We have four files left:
* `EquivGroupoids.v`
We've discussed this, and we seem to be in agreement that ripping out the lemmas here and placing them in appropriate areas will be a good idea. This should probably be discussed further in it's own PR.

* `FunextEquivalences.v`
There are various equivalences (mostly requiring Funext hence the name) that we haven't explicitly got in the library. I think we should discuss this further in it's own issue/PR.

* `Funext.v`
As I said before, most of this is in Metatheory, but there are a few things on AC in type theory. This is generally something that is missing from the library, so I will not delete this just yet until we discuss it further in its own issue/PR.

* `Pi1S1.v`
This is the "homotopy theoretic" proof of Pi1S1. The library has the "encode-decode" version. I'll make an issue/PR for this so we can discuss if we want this lying around somewhere.

Since we need to discuss the above further in their own separate issues, I will publish the PR currently.

**Comment by peterlefanulumsdaine** [comment]
I just went to have a more careful look at `Funext` and `FunextEquivalences`, and I realise that `Funext` and `FunextEquivalences` depend on some of the files deleted in the earlier #1339, so it’s difficult to even start on resurrecting them (or figuring out whether we want to) without at least temporarily restoring those other files as well.  Sorry I didn’t pick that up when I approved the earlier PR.  This is why having code that isn’t in the makefile is bad!

So I’ve prepared a new PR #1344 which I think finishes the job of clearing up `contrib/old`.  Most importantly, all files are either deleted or else are back in the `_CoqProject`/`Makefile`.

- `EquivGroupoids` is back in the `_CoqProject`, and at its old location at `theories/EquivGroupoids.v`; I will start a separate issue about re-homing its material.
- `Funext`, `FunextEquivalences`, and `Pi1S1` are deleted; I will start separate issues about possibly resurrecting them.

I know this leaves things in a non-ideal state (in particular, the location of `EquivGroupoid`), but I think it’s much better + easier to finish cleaning up this big mess first and then deal with those smaller messes separately, than to discuss the smaller ones while the big one is still muddying the waters.

**Comment by mikeshulman** [comment]
Sounds good, thanks!

**Comment by mikeshulman** [comment]
Could we configure our CI to check that all `.v` files are in the Makefile, so that this doesn't happen again?

**Comment by Alizter** [comment]
@mikeshulman  #1347

**Comment by peterlefanulumsdaine** [comment]
@Alizter : Thanks!  Continuing discussion on this point in the thread for that PR.
