### ISSUE TITLE
Using `reflexivity` with `Equiv` increases universe

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1356]
Using the `reflexivity` tactic with an `Equiv` goal causes a strictly larger universe to be postulated. This has unfortunately propagated universe growth in various areas. The following snippet demonstrates the problem:

```coq
Require Import Basics.

Axiom A@{i} : Type@{i}.

Axiom foo@{i} : A@{i} <~> A@{i}.

Definition bar@{i} : A@{i} <~> A@{i}.
Proof.
  reflexivity.
Fail Defined.
Abort.

Definition bar@{i} : A@{i} <~> A@{i}.
Proof.
  exact equiv_idmap.
Defined.
```

Since the instance for reflexivity for `Equiv` has to mention a relation `Type@{i} -> Type@{i} -> Type@{i}` it is no surprise that `reflexivity` increases the universe. However, this does mean various places where `reflexivity` is used to prove equivalences may be better served with specifying `equiv_idmap` exactly.

Is there a way to get `reflexivity` to not introduce a new universe here?

**Comment by mikeshulman** [comment]
I doubt it.  I think we should just use `equiv_idmap` explicitly.  I suppose we could enforce this by removing the `Reflexivity` instance for `Equiv`, but I'm not sure that's a good idea.

**Comment by Alizter** [comment]
I was going to suggest that we add a note to STYLE.md about this but it seems that has already been done! I'll keep this issue open this week in case anybody else wants to contribute to the conversation. It seems there is not much to do other than reading STYLE.md. I would consider this issue to be closed.

**Comment by SkySkimmer** [comment]
HoTT's `reflexivity` tactic is currently defined https://github.com/HoTT/HoTT/blob/7730a73f702caeaa8748227870f03815f032b414/theories/Basics/Overture.v#L66-L73
~~~coq
Ltac reflexivity :=
  Coq.Init.Notations.reflexivity
  || (intros;
      let R := match goal with |- ?R ?x ?y => constr:(R) end in
      let pre_proof_term_head := constr:(@reflexivity _ R _) in
      let proof_term_head := (eval cbn in pre_proof_term_head) in
      apply (pre_proof_term_head : forall x, R x x)).
~~~
`Coq.Init.Notations.reflexivity` is basically `constructor` since we don't load Coq's setoid stuff.

AFAICT it's just a typo making us cbn for nothing, for instance `symmetry` immediately after refines using the reduced term.
If we fix that, we can then do `Arguments reflexive_equiv /.` which will reduce the instance sufficiently. In other words,
~~~coq
Require Import Basics.

Ltac reflexivity :=
  Coq.Init.Notations.reflexivity
  || (intros;
      let R := match goal with |- ?R ?x ?y => constr:(R) end in
      let pre_proof_term_head := constr:(@reflexivity _ R _) in
      let proof_term_head := (eval cbn in pre_proof_term_head) in
      apply (proof_term_head : forall x, R x x)).

Arguments reflexive_equiv /.

Definition bar@{i} (A:Type@{i}) : A <~> A.
Proof. reflexivity. Defined.
~~~
succeeds.

**Comment by Alizter** [comment]
@SkySkimmer Nice! I will submit a PR fixing this later.
