### ISSUE TITLE
Importing WildCat breaks inference (for MonUnit)

### ISSUE THREAD

**Issue by jarlg** [HoTT/HoTT#1359]
I am working on implementing pullbacks of abelian groups [here](https://github.com/jarlg/HoTT/blob/01b582789f4f0d6a28e1709978883bdd7af9f3b2/theories/Algebra/AbGroups/AbPullback.v#L38), and it seems inference breaks for the line linked to if I import WildCat. To replicate, just add "Require Import WildCat." as line 3 and run the file.

My interest for importing WildCat is the "$->" syntax for GroupHomomorphism, but this inference issue means I can't.

**Comment by jdchristensen** [comment]
I don't know exactly what is triggering it, but if you replace `1` with `mon_unit` in both places, it works.

In general, natural numbers are much too overloaded in the library, and this is a common problem.  E.g. `1` can mean the natural number, the identity path, the unit of a group, the trunc_index, and other things as well, depending on scope.

**Comment by jdchristensen** [comment]
It also works to move the WildCat import earlier in the list of imports, so this probably has to do with which scope was opened most recently.

**Comment by Alizter** [comment]
Replace your `Global Open Scope mc_scope` with
```coq
Local Open Scope mc_scope.
Local Open Scope mc_mult_scope.
```

And it should work fine.

If you want to use mathclasses you need to open `mc_scope` then open the `mc_mult_scope`.

Generally we want to open scope locally so that files that import the current file don't end up opening those scopes. This can lead to trouble.

**Comment by Alizter** [comment]
The reason it didn't work at all before is because `trunc_scope` gets opened in `WildCat` which has caused `1` to mean a `trunc_index` rather than what ever mathclasses said. In fact this is done a lot earlier in `Types`. In general, it is good practice that you `Require Import Basics Types.` first before anything else. This would also fix your issue.

**Comment by jarlg** [comment]
Thanks for the fixes!

The "Global" was a bad search-and-replace I hadn't noticed, thanks. But even with everything Local (scopes and instances), importing WildCat on the 3rd line fails. Also after adding Types to the first import list; moving WildCat to the 1st import line solves it though. Thanks for the explanation, @Alizter!

**Comment by jdchristensen** [comment]
Is it a bug that when importing WildCat, trunc_scope is opened in the file doing the import?  As Ali said three comments up, we generally want to open scope locally...

(BTW, this isn't done in the WildCat folder, so it is an indirect effect of something that WildCat imports.)

**Comment by jdchristensen** [comment]
@jarlg If you open *both* mc_scope and mc_mult_scope, then it doesn't matter what order you do the imports.  I guess the 1 as the unit is part of mc_scope.

**Comment by jarlg** [comment]
@jdchristensen Yeah, I realized and edited my comment. :)

**Comment by Alizter** [comment]
OK I've sussed out why WildCat is being silly here. The "imports" of WildCat.Type are
```coq
Require Export Basics.
Require Export WildCat.Core.
Require Export WildCat.Equiv.
```
Which reexports the trunc_scope from Basics.
