### ISSUE TITLE
Subgroups vs subgroups upto isomorphism

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1387]
When designing the group theory library, I defined subgroups to be subgroups upto isomorphism. I thought that this would better fit the informal usage i.e. Z2 is a subgroups of S4 etc.

I don't think this is correct anymore however. It generalizes our definition of normal subgroup slightly. I think this may be a problem as evidenced here: https://mathoverflow.net/a/370104/54401

In that answer they construct a group whose subgroups are "normal upto isomorphism" but not normal. I think this is plenty evidence that "subgroup upto isomorphism" is strictly a weaker notion than subgroup.

To fix this we need to replace the definition of subgroup with one that uses a predicate. As a result the type of subgroups of a group G in a universe U will live in a strictly larger universe, but the actual group we get from this will still be in U.

**Comment by mikeshulman** [comment]
No, that question is about subgroups that are *abstractly* isomorphic to a normal one (i.e. not respecting the inclusion).  Our subgroups are *equipped with* an inclusion, so the resulting notion of "normal" is the same as the usual one.

**Comment by Alizter** [comment]
Oh I see where I was confused now. Being a normal subgroup is really a property of the inclusion map. I was confused because I thought we could always compose the subgroup with the isomorphism and get another normal subgroup, but that is no longer the same subgroup.

Alright, I will close this issue.

**Comment by mikeshulman** [comment]
Which isn't to say that we shouldn't switch.  As I think I said, I would have been inclined to do it the other way from the start.  The fact that we *can* talk about subsets directly, rather than injective functions, is one of the advantages of type theory over ETCS.

Also, am I confused or do *both* definitions of subgroup end up living in a higher universe (though, under propositional resizing, being equivalent to one in the same universe)?

**Comment by Alizter** [comment]
I've thought about this a bit more over the passing months, and I am more and more opting to redesign and define subgroups as a special kind of predicate on groups.

Currently we talk about subgroups like they are groups, but really we are talking of properties of their inclusion map. We can remove a lot confusion just by making it a property of a predicate on groups.

@jarlg I wonder what your opinion on this is. since you said you will be using the groups library. I personally think, we should seriously consider redesigning it before too much stuff depends on it.

**Comment by jdchristensen** [comment]
I don't think the current way is confusing at all.  Both ways of thinking of a subgroup (as a predicate on a group or as another group equipped with an inclusion map) are completely standard and reasonable mathematically.  So I don't think "removing confusion" is a good justification for changing things.  More important is how things work when formalizing.  Are there any particular things that would be simpler with the predicate definition?  (And any things that would be more complicated?)  The translation between the two is straightforward, so maybe it doesn't make much difference?  I think I have a slight preference for the current way, since it captures the essence of what you need:  a way to treat the subgroup as a group itself, and a way to regard elements of the subgroup as elements of the original group.  It seems less common to want the predicate.  And it's very common in practice for subgroups to arise from an abstract homomorphism (e.g. given a short exact sequence).  I'm also curious what @jarlg thinks.

**Comment by jdchristensen** [comment]
Possible things in favour of the predicate definition:  Maybe more things work out to be definitionally true?  Maybe it avoids some Funext and/or Univalence?  Those would all be good reasons for switching...

**Comment by spitters** [comment]
Subgroups as predicates as one of the main lessons for Gonthier from the formalization of the Feit-Thompson Theorem.

**Comment by jdchristensen** [comment]
The Gonthier formalization works with the assumption that *all* groups are subgroups of a common ambient group, which has weird consequences.  E.g. they can't form the direct product of two groups unless they happen to commute in this ambient group and have trivial intersection.  (Their direct product operation returns the empty set, which isn't even a group, if these conditions fail.)  I'm not sure we can conclude anything from their approach, since it is so different from what we are doing.

**Comment by jarlg** [comment]
It seems to me the main benefit of the predicate approach is that it simplifies equality of subgroups, which in turn lets us replace univalence with funext in a few places. I think predicates can be made almost as ergonomic as the current approach via coercions. If we define:
```Coq
Record Subgroup (G : Group) : Type := {
  subgp_pred : G -> hProp;
  subgp_unit : subgp_pred mon_unit;
  subgp_op : forall g h : G, subgp_pred g -> subgp_pred h -> subgp_pred (g * h);
  subgp_inv : forall g : G, subgp_pred g -> subgp_pred (-g);
}.
```
then we can construct the group structure on the total space, and coerce to it:
```Coq
Definition subgp_total {G : Group} : Subgroup G -> Group. Admitted.
Coercion subgp_total : Subgroup >-> Group.
```
This lets us treat a term `H : Subgroup G` as a group itself, and pick elements `h : H` (which project to elements of `G`). For example, this lets you treat the kernel of a map (as a predicate) as a group itself and the universal property then produces a map into `kernel f`, without any noise of total spaces (i.e. "actual" subgroups) being formed. The statement and proof of that fact remains basically the same, which is good.

With the record above, `equiv_path_subgroup` basically reduces to `equiv_path_sigma_hprop` and requires in particular only function extensionality, not univalence. Of course, the underlying statement is different: the current statement characterises paths as abstract group isomorphisms respecting the inclusions, and requires univalence for `equiv_path_group` among other things. This seems a decent improvement, but they're not widely used results.

Chasing things through, I think the following can be reduced to use only funext: `equiv_kernel_isembedding` (a group homomorphism is an embedding iff the kernel is trivial), and  `equiv_grp_image_embedding`. I've used the former result in developing short exact sequences, but it's not the only source of univalence and I doubt it'd let me only depend on funext entirely – I'll have to think more about that.

It seems to me that the stuff required to define quotient groups, i.e. cosets and congruence relations, will have similar complexity as it does now. Of course, what you can't do with predicates is treat an embedding literally as a subgroup. I guess this is the main argument against: you often encounter embeddings in the wild, not predicates. Can't think of any examples where that causes any actual pain however.

My impression is that the predicate approach simplifies things slightly, but I'm not sure to what extent refactoring will pay off.

**Comment by Alizter** [comment]
Regarding treating an embedding as a predicate subgroup, I think we can define an embedding record which is just a group homo and an injectivity proof, and coerce `i : G -> H` to `fun y => hexists x, i x = y`. So this should not be such a big issue.

**Comment by Alizter** [comment]
Also I think it would be better to directly have a predicate `G -> Type` rather than `G -> hProp` so that typeclasses can do the truncation work for us when we build subgroups.

**Comment by Alizter** [comment]
We can close this now that #1436 has been merged.
