### ISSUE TITLE
Our .git folder is huge

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1388]
### Issue

On the coq Zulip it was noticed that the git history file for the HoTT repo is larger than 600MB, for reference the .git history for the coq repo is 152MB.

This seems to be because we have a bot autoupdating static documentation for every commit to the `gh-pages` branch.

### Proposed solution

1. Move the `gh-pages` branch to a seperate repository.
2. Delete the `gh-pages` branch in this repository, this will delete all the history.
3. Configure the `gh-pages` branch in the new repository to autoupdate for every commit.
4. We could also add a new `gh-pages` branch back but only update documentation on each (coq) release. Though I am not sure how useful this would be.

@JasonGross I believe you know the most about this set up, what do you think?

**Comment by JasonGross** [comment]
Why not just clone with `--single-branch` or similar so that you don't fetch the gh-pages on cloning/fetching?

If that's not sufficient, I think it's fine to move the gh-pages branch to a separate repo, say, HoTT-gh-pages-history or something.  One possibility is that we could have the separate repo include all history, while in this repo we'd blow away the history of gh-pages on each commit.

**Comment by mikeshulman** [comment]
I think it'd be better not to expect casual users to know about something
esoteric like --single-branch.  (-:

**Comment by jdchristensen** [comment]
Wow, --single-branch reduces the .git folder from 625MB to 11MB!  I definitely think we should do something to make things work more efficiently by default.  In the meantime, is there a way to save this space in my current clone, without losing local branches, etc?  I tried
```
  git gc
  # .git is ~1GB here.
  git branch -d -r upstream/gh-pages
  git branch -d -r origin/gh-pages
  git branch -d -r jarlg/gh-pages
  # .git is ~1GB here.
  git gc
  # .git went from 1GB to 2.7GB!
  git reflog expire --expire-unreachable=now
  git gc
  # Still 2.7GB!
```
Not sure how git could blow up the .git folder just because I deleted some remote tracking branches!

**Comment by jdchristensen** [comment]
One more command helped a lot:
```
git gc prune=now
```
Now down to 383MB.

**Comment by JasonGross** [comment]
I was just about to comment with `git gc --prune=now`, but I see you found it first.  Running `du -h .git | sort -h` on my machine tells me that about 239M is in the submodule coq-HoTT, so that's probably a significant chunk of where your space usage is coming from.  If you get rid of tags (things shown by `git tag`) and then prune again, that might get rid of a bit more.

**Comment by jdchristensen** [comment]
I had some junk from worktrees.  With it gone, `.git/objects` is only 11MB, which is great, and the only other non-trivial thing is the coq-HoTT submodule, as Jason says.  It was 207MB, and by doing `git fetch --depth=1`, deleting most branches, deleting all tags, and running `git gc --prune=now`, I got it down to 130MB, still surprisingly large.  `git log` still goes back to 1999, for some reason.

Should our coq-HoTT submodule checkout use `--depth=1` or `--single-branch` to keep this small?

**Comment by mikeshulman** [comment]
My `.git` is 825M and `git gc --prune=now` doesn't shrink it at all.

**Comment by jdchristensen** [comment]
That command helped me after deleting the remote gh-pages branches.

**Comment by mikeshulman** [comment]
Ah, I see -- I had to `git branch -r -d <remote>/gh-pages` for all of my remotes.

**Comment by SkySkimmer** [comment]
So what shall we do?

**Comment by Alizter** [comment]
I was actually thinking about this today, after pruning 14GB from the .git folder. I think it will be better to move all the gh-pages stuff to a seperate repo.

**Comment by JasonGross** [comment]
I think we should probably modernize our GH Actions setup in the following ways:
- We should only build the library once with each version of Coq that we are testing, separating the build out into stages (perhaps one stage for building the main files, which will have master and 8.13; and another stage for doing all of the documentation generation, etc, depending on the relevant build)
- We should perhaps use the docker coq action for all the jobs
- We should move the publishing of files to dedicated GH Actions, as is now done for Alectryon (probably we should actually make a third stage, which uses the artifacts from the various second-stage jobs so that the publishing doesn't race)
- We should move the gh-pages branch to another repo which will maintain the history, and make the push to gh-pages be single-commit.  I think it is not so bad to keep the latest version on this repo, and it will make displaying docs from the wiki easier, but I agree that keeping the entire history of that branch on this repo is needlessly big.

I have [a workflow setup like this for coq-community/coq-performance-tests](https://github.com/coq-community/coq-performance-tests/blob/master/.github/workflows/coq.yml), though it uses an older version of JamesIves/github-pages-deploy-action with different variable names.  We may have to create a deploy key for GH Actions to use to push to the history repo.

**Comment by Alizter** [comment]
> We should only build the library once with each version of Coq that we are testing, separating the build out into stages (perhaps one stage for building the main files, which will have master and 8.13; and another stage for doing all of the documentation generation, etc, depending on the relevant build)

Can we do staging like the gitlab CI? I wasn't aware this was possible with github actions.

>We should perhaps use the docker coq action for all the jobs

This seems like a sensible step. It should no longer be our job to build coq.

>We should move the gh-pages branch to another repo which will maintain the history, and make the push to gh-pages be single-commit. I think it is not so bad to keep the latest version on this repo, and it will make displaying docs from the wiki easier, but I agree that keeping the entire history of that branch on this repo is needlessly big.

So the other repo will exist purely for historical reasons? Making the gh-pages be single-commit seems like a good step forward.

**Comment by Alizter** [comment]
OK, I've made a private repo in the HoTT organization that has our current copy of gh-pages. I've made this a private repo since nobody really needs to see it, and it would be more confusing to keep it public.

I will go ahead and delete the gh-pages branch on this repository. This should save a lot of space. The gh-pages action will continue to work as usual, but not have any history before. We need to eventually change this so that it only keeps a single commit and therefore doesn't waste time storing difs.

**Comment by JasonGross** [comment]
> I will go ahead and delete the gh-pages branch on this repository.

Please don't; that will break all the wiki doc links.  Just flip the booleans in the GH actions to force-push a single commit, and that will take care of things.  We should also set up the CI to keep pushing to that repo; it may be useful to have an explorable history of doc

**Comment by Alizter** [comment]
@JasonGross OK, I have already deleted gh-pages. But luckily that's why I made a back up.

**Comment by SkySkimmer** [comment]
Seems fixed? I get 24M for .git now.

**Comment by jdchristensen** [comment]
Yes, I get the same on a fresh clone, without specifying any special options.

**Comment by jdchristensen** [comment]
In my fork, I had to delete the gh-pages branch in order to make clones from there small as well.
