### ISSUE TITLE
Coq version confusion, or Require'ing HoTT breaks certain basic features

### ISSUE THREAD

**Issue by eric-downes** [HoTT/HoTT#1423]
The following (adapted form a Coq tutorial) works using hoqtop and coqtop 8.13.1:

```
Theorem double_mp_backwd : (forall A B C : Prop, A -> (A->B) -> (A->B->C) -> C).                       
Proof.                                                                                          
  intros A B C.                                                                                 
  intros pA AiB AiBiC.                                                                          
  refine (AiBiC _ _).
  exact pA.
     refine (AiB _).
        exact pA.
Show Proof.
Qed.
```

However, if I add: `Require Import HoTT.` above the `Theorem ...`, it complains on the second `refine` statement:
`Error: Expected a single focused goal but 2 goals are focused.`

This, even though no HoTT-features are being used.  I would expect requiing HoTT to not break anything unrelated?

I configured HoTT with Coq 8.13.1, and that is what `hoqtop --version` returns.  Is it secretly using an older version of Coq behind the scenes, or...

Thanks

**Comment by mikeshulman** [comment]
I believe this is due to `Global Set Default Goal Selector "!".` in HoTT.Basics.Overture, which we use to enforce marking all subgoals with bullets or braces when more than one is generated.  Arguably this is always better style anyway.

In general, the existence of global `Set` options in Coq means you can never trust anything to be completely "unrelated".  (-:  HoTT/Coq is designed as a *replacement* for the standard library, so you can't expect in general that tutorials or other Coq code written using the standard library will work under HoTT.

**Comment by eric-downes** [comment]
Thanks you!

That was very helpful.  The following works, in case anyone ever searches for the same problem:

```
Require Import HoTT.

Theorem double_mp_backwd : (forall A B C : Prop, A -> (A->B) -> (A->B->C) -> C).
Proof.
  intros A B C.
  intros pA AiB AiBiC.
  refine (AiBiC _ _).
  - exact pA.
  - refine (AiB _).
    + exact pA.
Show Proof.
Qed.
```

**Comment by mikeshulman** [comment]
You shouldn't even need the `+`.
