### ISSUE TITLE
Noise coming from native compiler option

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1489]
Unfortunately, the `-native-compiler ondemand` option creates a lot of noise when building the library with coq 8.13.2. This was introduced in #1474.

```
Warning: Native compiler is disabled, -native-compiler ondemand option
ignored. [native-compiler-disabled,native-compiler]
```

Currently there is no way to hide this warning but coq/coq#13821 fixes this issue.

I therefore think we should disable these arguments in our `_CoqProject` file and wait till coq 8.14 to re-enable them.

@JasonGross since this mostly affects you, is this the right way to go about it?

**Comment by JasonGross** [comment]
No, I think we should instead pass `-native-compiler no` until 8.14, and then switch back to `-native-compiler ondemand`.  If `-native-compiler no` still creates a lot of noise, I think we should just live with it, since I think it's better to have a lot of noise on some machines than to need to increase the library build time by many minutes on other machines and have to add the instructions "if you find that you are getting stack overflows from the command line when building the library, try passing `COQEXTRAFLAGS="-native-compiler no"`".  Alternatively, we could do some makefile hackery to detect how Coq was configured and set up the flag like that.  But I think this warning is a bug, I'll go report it.

**Comment by Alizter** [comment]
I think it is already reported as coq/coq#13819

**Comment by JasonGross** [comment]
That is a slightly different report.  I cannot tell if Emilio's comment at https://github.com/coq/coq/issues/13819#issuecomment-772763785 ever got implemented, so I've opened https://github.com/coq/coq/issues/14173
