### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1515]
We have a few stale branches that we should consider removing:

| Name | Last updated | Commits ahead | 
| --- | --- | --- |
hott-on-generic-equality  | Updated 9 years ago | 3 |
ssreflect | Updated 8 years ago | 0 |
stable.old | Updated 8 years ago | 1 |
v8.5 | Updated 4 years ago | 0 |
stable | Updated 4 years ago | 0 |
master-with-autoreconf-files | Updated 15 months ago by Travis CI User | 1

I don't believe that there is anything worth keeping here.

**Comment by Alizter** [comment]
@mikeshulman  @JasonGross what do you think?

**Comment by mikeshulman** [comment]
Hmm, probably?

**Comment by JasonGross** [comment]
I think you should turn `v8.5` into a tag if there isn't already a relevant tag, and then delete it.

Regarding `stable`, the idea was:
> That would be fine with me too.  In fact, on consideration I think I would rather not accumulate *branches* for old versions of Coq and keep them around indefinitely; that seems rather to be the role of tags.  So I suggest augmenting Andrej's proposal with a git tag for the "stable tip" that works with each official Coq release, with the `stable` branch always pointing to the most recent of these.

_Originally posted by @mikeshulman in https://github.com/HoTT/HoTT/issues/883#issuecomment-315722000_

Clearly we haven't followed this policy, but we could start doing that, instead of deleting `stable`?  On the other hand, we're trying to maintain `master` compatibility with both the tip of Coq master and also the latest release, so perhaps indeed it's no longer needed.

**Comment by JasonGross** [comment]
Idk about hott-on-generic-equality (what's on that branch?  who made it?), but it seems fine to delete ssreflect (given that it's 0 commits ahead) and stable.old.  Also fine to delete master-with-autoreconf-files now that we don't use autoconf any more

**Comment by mikeshulman** [comment]
Sounds fine.
