### ISSUE TITLE
The notation "p ^" clashes with the infix "_ ^ _" in the standard library

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#155]
These notations clash, even if they're in different scopes, which is annoying.  The only way, it seems, to get these notations to work together is to declare "p ^" to be at the same level as "_ ^ _", which happens to be level 30.  This breaks many other things, though...

**Comment by Alizter** [comment]
It has been a while since this was discussed, can anybody offer anything new in this discussion?

At the moment we are in a position where a lot of the library is reliant on the notation `^` and it looks to be a great pain to go and change all of these to `!`.

Personally I am not a huge fan of `!` since to me it suggests `¬` but I could be swayed otherwise. Are there any practical advantages to using `!` since it is a prefix notation?

Otherwise, if everybody is content with `^` we should close this issue.

**Comment by Alizter** [comment]
I will close this issue as it seems unlikely to be changed.
