### ISSUE TITLE
Importing HoTT library not working.

### ISSUE THREAD

**Issue by lgiito** [HoTT/HoTT#1642]
Cross-posting from [stackoverflow](https://stackoverflow.com/questions/71901565/importing-hott-library-in-coq). I'm trying to use `coq-hott` library in Coq, but the import won't work. I'm working in the container of the `coqorg/coq:latest` docker image. After starting the container I've done the following:

0. `opam install coq-hott` in the container's terminal.
1. Hooked up `vscode` to the container and installed the VsCoq extension there.
2. Set the paths to `_CoqProject` and `coqtop`.
3. Created the `_CoqProject` file with the following lines:
```
    -arg -noinit
    -arg -indices-matter
```
4. Checked the HoTT library location: `/home/coq/.opam/4.05.0/lib/coq/user-contrib/HoTT`

After creating the `*.v` file to test the library I got the following problems:

0. `Require Import HoTT.` gives
```
Cannot find a physical path bound to logical path HoTT.
```
1. `From HoTT Require Import Basics.` works, but doing `Check (2+2).` after that gives
```
The term "2" has type "trunc_index" while it is expected to have type "Type".
```
2. `From HoTT Require Import Algebra.` works but `From HoTT Require Import Analysis.` gives

``` 
Cannot find a physical path bound to logical path Analysis with prefix HoTT.
```

I don't understand this behavior at all. It is similar to [this stackoverflow question](https://stackoverflow.com/questions/70283920/how-to-import-coq-library-hott-in-coqide), but still different. Am I doing something wrong ?

According to `opam` the packages versions for `coq` and `coq-hott` are `8.15.1 [4.07.1+flambda 4.05.0]` and `8.15 [4.05.0]` respectively.

**Comment by JasonGross** [comment]
> 1. Require Import HoTT. gives [...]

This is expected, you want `Require Import HoTT.HoTT.`

> The term "2" has type "trunc_index" while it is expected to have type "Type".

What are you expecting here?  Try `Check (2*2)%nat.` (you might need to import more things.)



> 3\. `From HoTT Require Import Analysis.` gives
> 
> ```
> Cannot find a physical path bound to logical path Analysis with prefix HoTT.
> ```

This is because there's no "Analysis" module.  Try "Analysis.Locator" instead.

**Comment by lgiito** [comment]
Thank you. I haven't seen `Require Import HoTT.HoTT.` before.

**Comment by Alizter** [comment]
Perhaps the confusing thing here is that all module begin the the `HoTT.` prefix in the project. You don't have to write it this way however when you use `From HoTT Require Import ...`.

The reason we have a HoTT module in the HoTT project is because it is an index file. When you `From HoTT Require Import HoTT` you are importing the file `theories/HoTT.v`. Most folders also have their own index file such as subfolders of Algebra, Basics, Types etc.

The best way to copy our import style would be to look at existing files, e.g. the ones in Homotopy/. All you would have to do for your project is put `From HoTT ...` before the imports.

**Comment by lgiito** [comment]
Thank you for the explanation. I also don't quite get the relation between modules and folders in the /HoTT folder. There are folders like `Algebra`, `Analysis`, `Basics` etc, but apparently only some of them correspond to modules that can be imported.

**Comment by Alizter** [comment]
Folders never create modules, but they will create prefixes for modules. Having a folder A, and putting a B.v file in there will give the module name A.B. The reason some of our folders have modules is because there is a file explicitly exporting all the contents of that file. For instance have a look in `theories/Basics.v` it exports all the contents of the Basics folder. Same for many others.

In many cases we don't have an index file because there simply isn't enough stuff in a folder, this is the case for Analysis. Other times, it doesn't make sense to import an entire folder, e.g. Algebra.

**Comment by lgiito** [comment]
Now its clear, thank again.
