### ISSUE TITLE
From HoTT Require Import Foo. fails with several Foo's

### ISSUE THREAD

**Issue by SnarkBoojum** [HoTT/HoTT#1655]
Many lines looking like:
```
From HoTT Require Import Foo.
```
fail, with:
```
Error: Notation "~ _" is already defined at level 75 with arguments constr
at level 75 while it is now required to be at level 35 with arguments constr
at level 35. 
```
Among the bad `Foo`'s, there's `HoTT`, `Algebra`, `Basics`, `Categories`.

The failure in case of `Basics` is especially annoying considering it's the very first line of [this example](https://x80.org/rhino-hott/)!

Among the good ones, there's `Analysis.Locator`, `Basics.Nat`, `Categories.Adjoint`...

This is with HoTT V8.15 and Coq 8.15.2.

(notice: I'm trying to package HoTT for Debian and need to write simple tests to see if the compilation gave a good package.)

**Comment by Alizter** [comment]
Hi, you need to pass `-noinit` and `-indices-matter` in order to use HoTT. See the README.md. You can do this by putting
```
-arg -noinit
-arg -indices-matter
```
in your _CoqProject file.

The reason this is failing is because HoTT is incompatible with the Coq standard library which is loaded implicitly. If the `-noinit` argument is passed to Coq then it is not loaded.

`-indices-matter` is about the universe level of inductive types, which in order to be consistent with univalance, needs to be enabled.

When I try the jscoq example it works, mostly because -noinit is setup to be passed correctly. If you are trying this on your own in a project then set up _CoqProject as I indicated above. If are simply passing this to an editor, then you can pass `-noinit` and `-indices-matter` directly.

**Comment by SnarkBoojum** [comment]
Oh, my bad! Thanks, that settles the matter with me, I can proceed on getting it into Debian.

Thanks!
