### ISSUE TITLE
Basic group theory

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#654]
For something I'm currently trying to formalize, I need some very basic group theory (specifically, [Lagrange's theorem](https://en.wikipedia.org/wiki/Lagrange%27s_theorem_%28group_theory%29)).  I could just prove the special case of it that I need, but as time goes on we'll undoubtedly need more group theory.  Is there any existing library including group theory (with a compatible license) that we could steal from?  Or is the HoTT approach to things like hsets, subsets, images, and quotients so different from any other that that wouldn't save any appreciable work?

**Comment by vladimirias** [comment]
Basic algebraic hierarchy is formalized in UniMath. There are the concepts of a group and of a subgroup. There is a concept of a finite type (finset) and the function that assigns to a finset its cardinality in nat. Therefore it is very easy to formulate the Lagrange theorem. There are various theorems about the cardinalities of dependent sums of families of finite types that should make the proof of this theorem easy.

**Comment by mikeshulman** [comment]
I have Lagrange proved now [here](https://github.com/mikeshulman/HoTT/blob/groups/theories/Groups.v#L292), using a similar library of theorems about cardinalities of finite sets motivated by the one in UniMath (which I recall you demonstrating 5 years ago (!) at CMU).  I used the definition of "group" from #661 for simplicity, but it should be easy to adapt to any definition of group.

**Comment by JasonGross** [comment]
> Given cumulativity, is there really any point to having a separate `Unit` in each universe?

Universe variance isn't judgmental, at the moment.  So we don't get `IsTrunc@{i} -2 Unit` from `IsTrunc@{Set} -2 Unit`, and this causes many, many problems with theorems that expect to be able to put arbitrary below the universe of `IsTrunc`.

`DecidablehProp` would be fine, I guess.  (An instance of `Decidable` would need to be proven anew for each definition, by recursion.)

We can always define `sum_of_bool : forall b : bool, b = true + b = false`

**Comment by mikeshulman** [comment]
What do you mean by "put arbitrary below"?

I don't think we'd need to prove `Decidable` once per each definition; we could just make each definition recursive with values in `DecidablehProp`, supplying `DecidableUnit` or `DecidableEmpty` as appropriate (which I'd be tempted to try calling `True` and `False`...).  We could even make a coercion from `DecidablehProp` to `Bool` so that we could leave the `dec` out of `if...then...else`.

I'm not convinced that `sum_of_bool` would give quite the same benefits as matching on an instance of decidable.  The latter gives an actual inhabitant of the type in question, whereas the latter gives only an equality in `Bool` that you would probably then have to substitute or rewrite along, or maybe even do inversion on.

**Comment by JasonGross** [comment]
> What do you mean by "put arbitrary below"?

Typo, now fixed; it should have been "put arbitrary universes below".  That is, theorems that talk about `IsTrunc@{i}` and have `j < i`.

**Comment by mikeshulman** [comment]
What about just fixing the universes of the versions of `Unit` and `Empty` that inhabit `DecidablehProp`; would that cause the same problems?

**Comment by JasonGross** [comment]
It's not entirely clear to me.  I suspect we'll have to test it out and see how well it works?

**Comment by mikeshulman** [comment]
Well, in general this library *is* for experimenting, so my vote is to experiment with `DecidablehProp`.  But I'd be interested to hear any other opinions.

**Comment by andrejbauer** [comment]
I only have a general opinion, which is that it is better to have any group theory than no group theory -- as long as we don't get stuck in a compatibility hell.

**Comment by spitters** [comment]
Re: ssr putting things in bool. This is especially convenient for reflection of (larger) statements, they can then be proved by computation instead of reasoning, but I guess you knew this.

Re math-classes: I expect that removing setoids should not be difficult.
We collected some resources [here](https://uf-ias-2012.wikispaces.com/Type+classes).

@aspiwack just released a library on [finsets](https://github.com/aspiwack/finset) I have not had to time to look at it carefully.

**Comment by mikeshulman** [comment]
I see that @aspiwack uses decidable props rather than booleans, pointing to [Bob Harper](https://existentialtype.wordpress.com/2011/03/15/boolean-blindness/) whose argument is pretty much the same reason I would prefer decidable props.

What's a good example of something that can be proved by computation?  I bet that with a suitable definition of the boolean operations on DecidableHProp we could also do computation there.

**Comment by andrejbauer** [comment]
I was also going to point out Bob's "boolean blindness" criticism. We should use decidable propostions.

**Comment by aspiwack** [comment]
Dear all,

I can give some context to my choice of using decidable propositions rather than boolean. When I started toying around with construction which exploited decidability, I started using booleans because ssreflect did so with impressive success (despite my being already suspicious of booleans, especially after a class I taught last year, using Scheme, where I saw students struggle with booleans a lot). Using booleans, as it turn out, didn't work for me at all. It was painful, it was unpleasant and inelegant.

Ssreflect uses a system of reflection lemmas and views to give meaning to booleans (view intro patterns are available in Coq's development version (_e.g._ `intros x/view`) so this methodology can be used). In essence they split the decidable proposition into two parts. But I see no advantage of doing so. In effect, boolean propositions can be used like booleans whenever the need is felt as @mikeshulman says above (I've written the logical combinators I needed in [my library](http://aspiwack.github.io/finset/FinSet.Lib.DProp.html#lab29)).

**Comment by mikeshulman** [comment]
Thanks for the thoughts @aspiwack !  Can you comment on your choice to include `Denies` as a separate datum in the definition of a decidable prop, rather than just using `~ Holds`?

**Comment by mikeshulman** [comment]
(Sadly, a coercion `DProp >-> Bool` apparently doesn't allow us to use `if` on a `DProp`; apparently Coq isn't willing to apply coercions before checking that the argument of `if` belongs to a two-constructor inductive type.)

**Comment by mikeshulman** [comment]
Ok, I've got an implementation of decidable hprops.  In fact, I have two of them: [here](https://github.com/mikeshulman/HoTT/compare/dprop-funext) and [here](https://github.com/mikeshulman/HoTT/compare/dprop-nofunext).  In both cases, I was able to get rid of `BoolSortCoercion` and `path_b_true__of__is_true` and `implb_impl'`, while preserving the "proofs by computation".  The difference is in where to put funext: since funext is required for implication and negation to preserve hprops, if a `DProp` is required to always an `hProp` then basically anyone using `DProp` needs to assume funext.  The other option is to say that a `DProp` is only required to be an `hProp` if we assume funext; this makes it so users don't have to assume funext unless they need `hProp`s out, but is a bit more annoying in other ways, e.g. we can't have a global coercion `DProp >-> hProp` as it would violate uniform inheritance.  I'm not sure which is better; opinions?

**Comment by aspiwack** [comment]
About the `Denies` field. It was, again, not something I started with. It makes it possible to push negation down automatically like one instinctively does in classical mathematics. The rationale is that negation is quite of a bore, nothing can be done with it. So when I kept negation around, I typically had to summon decidability in order to apply duality laws or eliminate double-negation. The `Denies` field renders negation truly involutive. Its magic is at work, for instance, in the definition of [the `dforall` quantifier on lists](http://aspiwack.github.io/finset/FinSet.Lib.ListSet.html#lab23).

**Comment by andrejbauer** [comment]
Indeed, symmetry should help here. Can we get things done so that negation is involutive definitionally (and does that matter)?

**Comment by mikeshulman** [comment]
@aspiwack can you explain what is "magic" about `dforall` and how it depends on `Denies`?

**Comment by mikeshulman** [comment]
@andrejbauer I'd be surprised if you could get negation to be definitionally involutive, since the witness of decidability has to be carried around too, and symmetry on coproducts is not definitionally involutive.

@aspiwack how do you define implication?  I would want `Holds (A -> B) = Holds A -> Holds B`; do you take `Denies (A -> B) = Holds A and Denies B`?

**Comment by JasonGross** [comment]
I would prefer to not need `Funext` everywhere. How annoying is it to have to insert the coercion to `hProp` manually? Is there a way to get canonical structures to give us a coercion her.  (@spitters?)

Is it possible to get negation to be judgmentally involutive on concrete `DProp`s, much like `^op` was judgmentally involutive on concrete categories in 8.4?  Actually, you should be able to make negation judgmentally involutive on all `DProp`s by playing a trick: require both a decidability proof, and a symmetrized decidability proof, and swap them around on negation (see the `_sym` fields in `PreCategory` and `Category.Dual.opposite`).

**Comment by aspiwack** [comment]
Jason's trick for definitional equality is nice. With just the `Holds`/`Denies` thing, what you have (in my notations) is `Holds (DNot (DNot A))` is convertible to `Holds A`, which is good enough for me.

The "magic" in `dforall P l` is that it is defined as `DNot (dexists (DNot∘P) l`, and nevertheless `Hold (dforall P l)` simplifies to something of the form `forall x, P x`. It's really sweet.

For implication, I haven't had the occasion to play with it but my guess would be that indeed `Denies (A->B) ≜ Holds A /\ Denies B` is the best choice. My heuristic is to maximise the usefulness of the formulae as hypotheses.

**Comment by mikeshulman** [comment]
> How annoying is it to have to insert the coercion to hProp manually?

There isn't anywhere yet in the library where we need to make a DProp into an hProp, so it's hard to say.

**Comment by mikeshulman** [comment]
It should also be possible to declare a *local* coercion inside any section that's assuming funext.

**Comment by JasonGross** [comment]
I've looked at both of the branches, and would prefer the non-funext one.  (It might be possible to do some sort of mix, so that, e.g., we also have `DHProp` which is just `{ T : DProp & IsHProp T }` so that we can prove `ishprop_code_nat` without induction, by making `code_nat` land in `DHProp`.  Implication will only exist for `DProp`s, but things like `dand` and `dor` will also have `DHProp` versions, and `True` and `False` will be `DHProp`s.  But this might be more work that is useful.

Also, it should be possible to prove `Univalence -> IsEquiv dprop_to_bool`, right?

**Comment by mikeshulman** [comment]
Will there be a lot of things like `code_nat` that end up being hprops without funext?  If so, then it might be worth trying the mixed approach.

**Comment by JasonGross** [comment]
The only things that won't be are implications that need to be coded as function types rather than "B or not A", right?  I can't imagine there are many of these, just the occasional property like transitivity where we can convertability---and even then, we can have something the goes between "B or not A" and "A implies B".  So, in normal usage, it seems like we shouldn't need funext?  (And we can even make a coercion from dimpl to funclass, so that we can "apply" things like "B or not A", perhaps?)

**Comment by mikeshulman** [comment]
Well, "B or not A" is going back along the road towards Booleans, so I'd like to avoid it.  Also "not A" is not an hprop without funext either, although I suppose if "or" means `hor` then "B or not A" is an hprop whether or not "not A" is.

Another (slightly weird) option would be to define `dimpl A B` to be `merely (A -> B)`, and likewise for negation.  Then it would always be an hprop whether or not we have funext, and would also retain the form of the logic, and we could probably coerce it to funclass as well.

Although we should consider how our choice will interact with #573; if we institute a `HITs` dummy typeclass, then using HITs to avoid funext won't help.  And in fact, if we resolve #573 that way, then `dor` will start having the same problem that `dimpl` and `dneg` have now, and even worse since it can't even be *defined* without a HIT.

Actually, how important is it that decidable propositions be *mere* propositions anyway?

**Comment by mikeshulman** [comment]
> Also, it should be possible to prove `Univalence -> IsEquiv dprop_to_bool`, right?

Yes, I've added that now to the [dprop-nofunext branch](https://github.com/mikeshulman/HoTT/compare/dprop-nofunext).

**Comment by andrejbauer** [comment]
> Actually, how important is it that decidable propositions be mere propositions anyway?

I was about to ask the same thing.

**Comment by spitters** [comment]
@mikeshulman asked:
> What's a good example of something that can be proved by computation?

Computing with the booleans will be faster than reasoning. Since our proofs are relatively small, it may not be an issue. The compilation of the entire library will be slower too.

**Comment by JasonGross** [comment]
> Actually, how important is it that decidable propositions be *mere* propositions anyway?

To have the chain categories be right, `leq` must be a mere proposition.  But in general, *shrugs*, I'd need to see more use-cases.

**Comment by JasonGross** [comment]
> What's a good example of something that can be proved by computation?

The typical example is proofs about concrete numbers.  A built-in computational univalence/HIT reasoning principal would, perhaps, allow us to prove the fundamental groups of the spheres by computation.  Proof by reflection is a systematic was of convincing the type-checker to solve your proof obligations for you ("by computation"), so that you don't need to carry big proof terms around.  (Perhaps surprisingly, it turns out that reconstructing the entire proof (but without building a proof tree along the way) is often faster than checking that an appropriate proof-tree is well-formed.)

**Comment by mikeshulman** [comment]
Of course, if dprops aren't hprops, then `dprop_to_bool` isn't an equivalence even with univalence.  But if they are, then logical equivalence is equality, and so we can `rewrite` along it; do I remember correctly that ssreflect sometimes likes to rewrite along decidable logical equivalences?

**Comment by mikeshulman** [comment]
I'm going to summarize this spaghetti thread and put it out of its misery; we can open new threads for more specific discussions.  Our overall conclusion seems to be to learn things from ssr, but not copy their code; in particular we will use decidable hprops rather than booleans, and #683 has now been merged.  Anyone who wants to add more theorems about nat, for instance, probably the best thing to try first is to look at ssr and then do it with dprops instead of bool.  For algebraic structures, we may try to copy some stuff from mathclasses if it turns out to be easy to replace setoids by hsets.
