### ISSUE TITLE
Why are basic types put in `Type1`?  /  Do we still need to prohibit `Set`?

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#774]
Various basic types are declared by hand to live in `Type1`, e.g.

```
Inductive Empty : Type1 := .
```

Since `Type1` is universe polymorphic, the effect is that `Empty` also is, with instances of it living in every universe strictly above `Set`/`Type0`

```
> Check Empty.
Empty@{Top.173}
     : Type1@{Top.173}
(* Top.173 |= Set < Top.173
              Prop <= Top.173 *)
```

(`Bool` is treated similarly, but not `nat`, which is monomorphic and lives in `Set`, since it’s imported from `Coq.Init.Peano`.)

Two alternative options (while still avoiding `Prop`) would be to have it declared just in `Set`/`Type0` (but of course coercible to higher universes), or to have it unrestrictedly universe polymorphic, living in all universes (possibly except `Prop`).

Why do we excise it from `Set`?  There’s certainly been discussion of this before, but all the bits I recall were from before universe polymorphism, and seem no longer relevant; and the only documentation I can find now is “In trunk, universes will not be unified with [Set] in most places, so we want to never use [Set] at all.” (in [Basics.Overture](https://github.com/HoTT/HoTT/blob/b381e5b04f3de2c5d8bc62399ac90f3ee8ba74db/theories/Basics/Overture.v#L74)), which seems rather unclear.

If we do still have reasons for this, it would be good to document them more clearly.

If we don’t, then it would be nice to make the basic types more polymorphic as described above; this would allow easier interoperability with developments that make explicit use of `Set`.

(A related question is: why do we excise these types from `Prop`?  The old answer to this seems still valid: `Prop` gets special treatment in Coq’s type system, in several ways whose semantics are rather unclear, so we want to avoid contact with it entirely.  `Set`, by contrast, gets no special treatment now, if I recall correctly, except of course under `--impredicative-set`.)

**Comment by mikeshulman** [comment]
Related: #754.

It seems to me to hinge on the question of whether `Set` really does get special treatment.  The comment you quoted from Overture seems to suggest that it _does_ get special treatment in some way, but that comment is equally opaque to me.  Can someone explain it?

One could, of course, just experiment with your suggested changes and see whether they break the library somewhere.

**Comment by peterlefanulumsdaine** [comment]
Yes — playing around with them today, the changes I suggest do turn out to break things, in ways that I don’t fully understand and can’t find a simple fix for.

Essentially, it seems `Set` does get some sort of special treatment vis-à-vis universe polymorphism: sometimes (but not always), if universe parameters in a definition can be instantiated as `Set`, then they will be, instead of being left generalised.

For example: define a couple of “polymorphic universes” `Type0`, `Type1`, along the lines of the current `Type1`, `Type2` in trunk (but not current `Type0`, which genuinely is fixed as `Set`):
````
Set Printing Universes.
Inductive DummySet : Set := DummySet_constructor.

Definition Type0 := Eval hnf in let gt := (DummySet : Type@{i}) in Type@{i}.
Arguments Type0 / .
Identity Coercion unfold_Type0 : Type0 >-> Sortclass.

Definition Type1 := Eval hnf in let gt := (Set : Type@{i}) in Type@{i}.
Arguments Type1 / .
Identity Coercion unfold_Type1 : Type1 >-> Sortclass.
```

These are both polymorphic, as desired:

```
> Print Type0.
Type0 = Type@{Top.401} : Type@{Top.401+1}
(* Top.401 |= Set <= Top.401 *)
Type0 is universe polymorphic

> Print Type1.
Type1 = Type@{Top.404} : Type@{Top.404+1}
(* Top.404 |= Set < Top.404 *)
Type1 is universe polymorphic
```

But now define axioms in these universes:

```
Axiom A0 : Type0.
Axiom A1 : Type1.
```

`A1` is polymorphic, as hoped.  `A0` also claims to be, but is not:

```
> Print A0.
*** [ A0 : Type0@{Set} ]
A0 is universe polymorphic

> Print A1.
*** [ A1 : Type1@{Top.410} ]
(* Top.410 |= Set < Top.410 *)
A1 is universe polymorphic
```
I have no idea why.  Explicitly specifying `Axiom A0 : Type0@{i}` makes `A0` polymorphic, analogously to `A1`.

In practice, this happens in e.g. the definition of `isHProp_Empty`.  If `Empty` lives in `Set` — not even if it *exclusively* lives there, but if it *can* be instantiated there — then the current definition of `isHProp_Empty` comes out with the monomorphic type `IsTrunc@{Set} (-1) Empty@{Set}`.  This bites you down the line, when you find yourself with a goal like `IsTrunc@{Top.123} (-1) Empty@{Set}` (arising by reduction from a goal like `IsTrunc@{Top.123} (-1) (SomeFam (inl a))`, where `SomeFam : A + B -> Type@{Top.123}`), and there’s a constraint that `Set < Top.123`; now `isHProp_Empty` can’t be instantiated to this goal.

Once again, one can add some universe annotations in the definition of `isHProp_Empty` to make it come out polymorphic.  But it seems like one will have to keep on making such annotations in (not all, but many) definitions downstream from `Empty`; and as the universe-polymorphicity of definitions grows, making these annotations (and finding where they need to be made) becomes at best increasingly cumbersome, and eventually I think rather non-trivial.

So in sum, it seems that universe indices often get specialised to `Set` in definitions, if they can be, instead of being left as general as possible, as they usually are otherwise.

Does anyone understand this better, or know the reasons for it?  @mattam82 ?

**Comment by JasonGross** [comment]
I think the only things special about `Set` are that (a) it's global and (b) there's nothing that lives below it.  Normally, if you have `U_i <= U_j`, and no other interesting constraints, it's relatively safe to unify them during minimization.  Then, later, you just instantiate them both with whatever universe you need.  But if one of them is `Set`, then this unification is a genuine restriction.

@mattam82, am I correctly recalling that there is code to not unify some kinds of universes with other ones unless absolutely required?  Is it possible that `Set` and `Prop` are misclassified? Or am I thinking of the wrong bit of code?

**Comment by mattam82** [comment]
Universe levels in general are not unified unless absolutely necessary, however, minimization will collapse Set <= i to i = Set unless the i has been introduced explicitely by the user (writing Type or Type@{i} for example).

**Comment by JasonGross** [comment]
Would it harm the minimization code to special-case `Set` and `Prop`, so that `Set <= i` is collapsed to `i = Set` only if `i` does not appear anywhere in the type signature of the constant?  Alternatively, if we just want to test this behavior, how about a flag like `Unset Aggressive Universe Minimization` or something, that makes Coq never collapse `Set <= i` to `i = Set`?

**Comment by mikeshulman** [comment]
It sounds to me like @mattam82 is saying that `Set` is *already* special-cased, so why not just a flag that turns off that special treatment?

**Comment by mattam82** [comment]
It's not a special case, it just naturally happens because you're often in a case with a single constraint Set <= i on i. I can easily special case on Prop and Set to avoid lowering universes to them indeed. That's one way to solve this issue. Another is to make cumulativity go through inductives, as Amin Timany is doing: https://distrinet.cs.kuleuven.be/people/amin

**Comment by mikeshulman** [comment]
Okay, I don't understand your previous comment then.  If collapsing Set <= i to i = Set is not a special case, then why does it happen when it isn't "absolutely necessary"?

**Comment by mattam82** [comment]
It happens during minimization, just not as a special case... It should *not* happen because of some "not-absolutely-necessary" f@{i} ~= f@{Set} constraint. Is it clearer? I'll make a longer explanation as part of a doc of the current system. We discussed fixes for the remaining issues (essentially regarding Prop and Set and this one in particular), I might get to all of them before vacations in August but I can't promess :)

**Comment by mikeshulman** [comment]
Okay.  Thanks!

**Comment by spitters** [comment]
@amintimany what is your solution "to make cumulativity go through inductives" ?

**Comment by amintimany** [comment]
Here is how I think it would help.

Let's say we have a category `C: Category@{i j}` where `i` is the universe level for the type of objects and `j` the universe level for the type of morphisms.
Now if we want to type check `C : Category@{k l}` (with cumulative inductive types) we get the constraints `i <= k` and `j <= l` as opposed to `i = k` and `j = k` that we would get in the current version of Coq.

This would help if `i` was `Set` (perhaps set due to some minimization). In this case, even if we have a constraint `Set < k` while trying to type check `C : Category@{k l}`, the new constraint set `Set <= k` is possibly satisfiable while `Set = k` is not.

So I think what is really helping here in general is the information on the variance of the universe variable in question which in this case comes from cumulativity for inductive types.

**Comment by spitters** [comment]
OK. The paper is [here](http://advent-project.eu/pubs/cit-ictac15.pdf). I now recall that I have seen it before. Just to be clear: it contains quite a bit of theory, but not all of Coq's theory (yet?) and it has not been implemented in Coq yet?

**Comment by amintimany** [comment]
Well we extend _predicateive Calculus of Inductive Construction (pCIC)_ which is technically the foundation of Coq. No it has unfortunately not been implemented yet. This is something that I would like to do in the hopefully-not-too-distant future.

**Comment by mikeshulman** [comment]
@peterlefanulumsdaine, is this issue closed by #813?

**Comment by SkySkimmer** [comment]
Bool is also Type1, possibly others too.

**Comment by mikeshulman** [comment]
Any reason not to put Bool in Set just like Unit and Empty?

**Comment by SkySkimmer** [comment]
So the following types are explicitly defined in Type1:
- a copy of `nat` in Tests for #754 (probably intended to stay there)
- `Pos` and `Int` from Spaces/Int.v (could be switched to Type0 AFAIK)
- `Bool` from `Types/Bool.v` (same)
- `CardinalityRepresentative` from `categories/NatCategory.v` (defined as sums of Empty and Unit, so Type1 used to be forced)
- `interval` from `hit/Interval.v` (unless HITs need Type1 this could be Type0 as well)
- `Identity_Modality` from `Modalities/Identity.v`(I don't think I want to touch this, but maybe it's less scary than it looks?)
- and a comment in `hit/Circle.v` says
```
Private Inductive S1 : Type1 :=
| base : S1
| loop : base = base.
```
  but the actual definition is `@Coeq Unit Unit idmap idmap` which ends up at a free floating universe (used to be Type1 due to Unit).

Should I change some of these to Type0?


NB: Type2 and Type2le are used only for modality stuff, and Type3/Type3le not at all.

**Comment by Alizter** [comment]
It looks to me like all the types mentioned are in Type0 therefore I am closing this issue. Feel free to reopen if I am wrong.
