### ISSUE TITLE
When autogen.sh falls back on git, it always gets latest version of autoreconf files,

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#780]
I was trying to build an old-ish version of the library, and found it failing (even after checking out a clean repo copy) with the error:

```
No rule to make target `_CoqProject', needed by `am-all'.
```

It seems the issue is that when `autoreconf` is not available, and `autogen.sh` falls back on `git` to get the `autoreconf` files from `master-with-autoreconf-files`, these files always correspond to the current tip of `master`.  So for building an older version, those files may longer work.  (In particular, I was on a version from before the repo was using a `_CoqProject` file.)

For anyone else dealing with this issue, the “workaround” I found was just to install `autoreconf`.  If you’re on a Mac and using Homebrew, `brew install autoconf automake` should do the job.

**Comment by andrejbauer** [comment]
I am inclined to reject this pull request.

The correct solution (which I implemented a long time ago but it got shot down by @JasonGrosss on the grounds that it polluted the commit logs) is to simply store with each commit the needed files in some `etc/stuff` directory. The script can then get them easily. If we can pull this off without polluting the commit logs, that would be great.

A lesser solution is to check whether the user is trying to compile the tip. If so, the script can fetch the missing files, but otherwise it should die.

**Comment by peterlefanulumsdaine** [comment]
Both of those sound like much better long-term solutions.  If someone can quickly implement one of them, then I would support rejecting my PR in favour of that.  If however that’s non-trivial and no-one has the time for it now, then I feel the warning message is better than nothing in the interim.

**Comment by mikeshulman** [comment]
Is it actually possible to do anything _now_ that will fix the problem for people trying to compile _older_ versions of the library?

**Comment by JasonGross** [comment]
We can add a target to the Makefile that emits a warning if autoreconf is not found, and .git exists.

**Comment by JasonGross** [comment]
(There's another issue which is that the script doesn't correctly get the latest version once it's already found a version, because it'll keep checking them out from the old version of the branch; we should remove the `git checkout $BRANCH $FILES` line and move the subsequent lines out of the `if` statement.)

**Comment by andrejbauer** [comment]
@mikeshulman has a point. I suppose we're fixing the future versions, not the past ones.

**Comment by Alizter** [comment]
I am closing this unless anybody objects.
