### ISSUE TITLE
Categories development not included in HoTT.v

### ISSUE THREAD

**Issue by kristinas** [HoTT/HoTT#789]
Can the files detailing the category development in theories/categories be added to the HoTT.v file so that they are available to the user by just saying Require Import HoTT?

**Comment by JasonGross** [comment]
I think this was an intentional choice.  You can get all of categories with `Require Import HoTT.categories`, if I recall correctly.

**Comment by kristinas** [comment]
I don't think so: things from the file Category/Morphisms.v are not recognized and the file does not seem to be included in categories.v.

**Comment by kristinas** [comment]
More precisely: The lines

Require Import HoTT.
Require Import HoTT.categories.
Check inverse_unique.

generate an error saying the reference inverse_unique was not found in the current environment.

**Comment by andrejbauer** [comment]
If stuff is missing from categories then I'd look into fixing `Require Import HoTT.categories`. It's probably not a good idea to import *eveyrthing* from `HoTT`.

**Comment by kristinas** [comment]
Okay. Can someone fix the Require Import HoTT.categories then? I don't have the confidence to do it myself.

**Comment by kristinas** [comment]
Also, what exactly is the difference between saying Require Import HoTT.categories. and Require Import categories.  ?
Both seem to work.

**Comment by JasonGross** [comment]
Try
```coq
Require Import HoTT.categories.
Locate inverse_unique.
Check Category.inverse_unique.
`

**Comment by JasonGross** [comment]
`Require Import HoTT.categories` and `Require Import categories` are the same, so long as there is only one file named `categories.v`.  If there are two files named `categories.v`, then the latter is ambiguous.

**Comment by kristinas** [comment]
The snippet you gave above works. But how come one needs to prefix inverse_unique with Category?

**Comment by JasonGross** [comment]
Yes, this is also intentional.  If you do
```coq
Require Import HoTT.categories.
Import Category.
```
(or maybe `Import HoTT.categories.Category`?), you can use `inverse_unique` unprefixed.  There are many concepts that show up in multiple places; if you say `dual`, does this mean the dual of a category, or a functor, or a natrual transformation.... If you say `inverse`, is this an inverse morphism, or functor, or natural transformation?  Does `left_identity` mean the left identity law for morphisms, or for functors?  When you ask for a product, is it a product of categories, or of objects, or functors, etc?  Rather than qualifying names with underscores, or choosing a haphazard ordering of imports, you only get the qualified names by default.  So you need to say `Category.left_identity` or `Functor.left_identity`.

**Comment by kristinas** [comment]
Thanks, that makes sense!

**Comment by JasonGross** [comment]
I'm going to close this issue; feel free to reopen or open a new one if this isn't resolved.
