### ISSUE TITLE
graphs

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#796]
New version of [dpdgraph](https://github.com/karmaki/coq-dpdgraph) is out.
We may want to update, and perhaps depend on opam for install???

**Comment by JasonGross** [comment]
Probably not until 8.5pl1, given that HoTT compiles 3x slower on 8.5 than on 8.5beta2.  Also, I'd rather not depend on opam on Travis, given that this would require building all of Coq, if not all of OCaml, every time we test (rather than installing the binaries with `apt-get`, or building just the Coq binaries and not the standard library).

**Comment by andrejbauer** [comment]
Isn't there some new scheme for Travis that lets us skip all the installation stuff?

**Comment by JasonGross** [comment]
Oh, it's probably reasonable to cache the builds of (OCaml and) Coq ... if we can get them to build once, which I'm not sure we can, given the 50 minute time-limit.

**Comment by andrejbauer** [comment]
Is it possible to go beyond the limit if we pay money?

**Comment by JasonGross** [comment]
Sorry for the delayed response.  Last time I asked, the answer was "no".

**Comment by spitters** [comment]
We are now waiting for:
https://github.com/coq/coq/pull/6493

**Comment by SkySkimmer** [comment]
That was merged last year (if barely last year) though?

**Comment by spitters** [comment]
So, we should update to the new Coq version, and do a new opam release ?

**Comment by ejgallego** [comment]
This seems stale or easy to solve I think. Also, if you need more powerful CI I suggest you switch to gitlab.

**Comment by spitters** [comment]
Closing this, as meanwhile we've moved to a newer Coq version
