### ISSUE TITLE
Questions about assumptions in library.

### ISSUE THREAD

**Issue by georgydunaev** [HoTT/HoTT#802]
1. Is it true, that no additional assumptions, except univalence axiom(and funext), were made during the creating of this library? 
2. I want to verify "simplicial model of univalent foundations" paper. It mean that I should avoid using univalence axiom(but can use funext) in order to obtain good proof, which is not just another test of consistensy of HoTT, doesn't it?

This question possibly should be clarified by myself, but I want to save some time at this stage.

p.s. Did I correctly understand that questions about library better to be asked here than in HoTT cafe?

**Comment by andrejbauer** [comment]
1. If you run `grep -re '^ *Axiom' theories` it tells you which axioms are used, and there are a number of them. For instance, higher inductive types such as the circle use axioms.

2. The simplicial model is constructed in the realm of set theory. I would imagine that in order to verify the paper you would be better off with a proof assistant that is based on set theory, such as Isabelle?

**Comment by mikeshulman** [comment]
Regarding 2, I would say that the simplicial model is constructed in _informal_ set theory, so it ought to be formalizable inside the hsets of HoTT just as well as in any other context.  The only wrinkle is that the category of hsets is not an hset, but I think the simplicial model treats the category of sets (and related categories like simplicial sets) "categorically", so this shouldn't be an issue.  In fact, I thought at some point Vladimir also had some interest in formalizing the simplicial model inside UniMath.
