### ISSUE TITLE
Metacategories.

### ISSUE THREAD

**Issue by georgydunaev** [HoTT/HoTT#832]
Should the trunc_morphism be separated from record which is currently know as Precategory?
(In order to implement notion of MetaPreCategory, similar to https://proofwiki.org/wiki/Definition:Metacategory)
It possibly should be done if we want to use enriched categories, shouldn't it? (also n-categories and even (oo, 1)-categories?)
I've tryed to create solution, which changes Category/Core.v only, but without good result.

**Comment by georgydunaev** [comment]
I've almost done it, but have little issue:
How to prove goals like equality of records?
 {| pcm := q0; trunc_morphism := w0 |} = {| pcm := q1; trunc_morphism := w1 |}

**Comment by JasonGross** [comment]
See https://github.com/HoTT/HoTT/blob/master/theories/Categories/Category/Paths.v for a way of doing equality systematically for a particular record.

**Comment by mikeshulman** [comment]
Or https://github.com/HoTT/HoTT/blob/master/theories/Types/Record.v for a
general method that works for all records.

**Comment by JasonGross** [comment]
I tried using the method / code from Record.v in https://github.com/HoTT/HoTT/blob/master/theories/Categories/Functor/Paths.v and found it too slow.

**Comment by georgydunaev** [comment]
Finally I had time. 
Solution: https://github.com/georgydunaev/HoTT/commit/6f1f2387fb6c72acf175701fd6e98ea84f6ec536 . That's a working draft. (Few theorems are commented. Some proofs are changed. Solution for slices is not beautiful.  I mean notation "Functor / (from_1 _ object)" instead of "Functor / object". )

**Comment by georgydunaev** [comment]
Maybe it is more preferable to create duplicates of all files with metacategories, metafunctors, etc? How do you see acceptable way to implement metacategories?  Do you think that it is worth to be done?

**Comment by peterlefanulumsdaine** [comment]
Investigating precategories with the `trunc_morphism` removed is certainly potentially interesting.  For comparison, in `UniMath`, the main definition of `precategory` doesn’t include the analogue of `trunc_morphism` — and while I’m not a fan of that as a design decision overall, since the assumption then has to be explicitly assumed in so many places, it is interesting to see which things don’t require `trunc_morphism`.

As you say, it can also be a step towards defining *n*-categories (at least, saturated ones — for non-saturated ones, one would also need to drop or change the associativity etc. components, since they’ll be given in terms of higher cells, not equalities).

However, I’m not sure that dropping `trunc_morphism` really corresponds to the traditional distinction between categories and meta-categories.  The traditional distinction is the *size-restriction* sense of “is a set”, while `trunc_morphism` is the *dimension-restriction* sense of “is a set”.  So it seems maybe a little misleading to call these meta-(pre-)categories?

**Comment by mikeshulman** [comment]
Yes, that's right.  And actually, I think that meaning of "metacategory" is
a bit archaic anyway.

**Comment by Alizter** [comment]
While #1113 is still an issue, we have in the mean time the wildcat library which should be sufficient to close this issue.

Feel free to reopen otherwise.
