### ISSUE TITLE
Set comprehension in Classes

### ISSUE THREAD

**Issue by abooij** [HoTT/HoTT#933]
Upon importing `HoTT.Classes.interfaces.canonical_names`, set comprehensions such as `{ x : A & B x }` don't work. I suppose this is because of the notation introduced for `&` on lines 110-113. Is there an easy way to fix this, or is there a workaround?

**Comment by SkySkimmer** [comment]
Workaround: notation `{x : A | B x}` is equivalent.

Easy fix: not that I can see.
If we move infix `&` from level 50 to level 201+ the `{ x : A & B x }` notation works but uses of `&` break.
Sadly closing the scope doesn't work.

We could break from mathclasses and change the notation for sg_op, or maybe make it local to where we  use it since I don't think it's that many places.

**Comment by abooij** [comment]
Ah thanks, I didn't realize that workaround! Thanks for the quick reply.

I was a bit confused by the fact that code that works elsewhere in the HoTT library doesn't work in the Classes subdirectory. So I would be in favor of some solution, if it's not too much trouble :)

**Comment by Alizter** [comment]
This is related to #976.

**Comment by Alizter** [comment]
The following seems to work:
```coq
Require Import Basics.
Require Import Classes.interfaces.canonical_names.

Context (A : Type) (B : A -> Type).

Check {x : A & B x}.
```
therefore I am closing this issue. Not sure what fixed it.
