### ISSUE TITLE
Math classes is a bit of a mess (and in general the whole library)

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#962]
Can we organise the classes folder into a bit more of an intuitive set of files? Especially if we are to use them in the future. For example suppose you want to formalise something about groups, you go into the HoTT folders and find the classes folder. From here it is not entirely clear where you can find theorems and definitions relating to groups. Some files are really spread out, some files are super compressed (take abstract_algebra.v).

Now I understand that this is a port of a coq library but I don't believe it's in a usable state as it stands. In fact I don't think I've found a single file outside of classes using anything in it. It's just there.

I would argue that this isn't really a "port", more of a fix to get things working (what working and why?).

I propose the following project(s): 

1. We reorganise this area, preferably call it something other than classes. Thin out the files so if I want theories and definitions about groups I simply go to the group folder and find the files. Jason's category library is probably a good structure to follow.

2. We start to use this elsewhere. For example in the HIT folder there are a few results about homotopy groups but I haven't seen an outright definition of it. Maybe we should create a homotopy folder instead like in the agda formalisation. In it we can define many of the tools for synthetic homotopy theory. And if we are still insistent of keeping the HIT folder we can keep it. (however I am not a fan of this idea as other formalisations also use private inductive types but they are organised nicely(er).

3. Organise the whole library to be as nicely organised as the categories library.

If this is to be the HoTT library for Coq, then it stands to reason that one should be able to easily to mathematics with it. But for now we have this weirdly organised blob of files.

There is of course an aurora of "UniMath" in the air however it has been said before that the library is open to contributions but has no overall goal of becoming UniMath. Which is fine, but what I am suggesting is that we make it easier to maintain and add to. 

Anyway sorry if this is a bit of a rant but it has been bugging me for some time, and I can't be the only one. And this post reads like an attack on the classes folder but really its about the whole library. This is a slightly impossible project to do individually, hence the project proposal.

**Comment by mikeshulman** [comment]
I certainly agree that we should start using the classes machinery elsewhere wherever appropriate; I think this just hasn't happened since no one has done much development on this library recently for which it would be useful.

I'm kind of inclined to say, though, that the classes subdirectory should stick as close as possible to the main version of the classes library, to make it easier for the maintainers to port updates.  So maybe you should take up your complaints about its organization with the authors of the classes library.

**Comment by mikeshulman** [comment]
If you're also complaining that the HoTT library as a whole is poorly-organized, I'm surprised; we've made a significant effort to organize things into appropriate files and subdirectories as explained in the STYLE file.  What in particular is it that bothers you about the organization?

**Comment by Alizter** [comment]
Maybe I got a bit lazy writing the whole library, but there are definite places we could improve. Reading back my writing I think it is being a bit too harsh. I really appreciate the work you guys have done so I want to change the tone of my writing to suggestion rather than frustration.

I think one of the key issues is documentation. Which I know is very difficult to write effectively. As it stands the autogenerated documentation probably scares most people away.

I think we should have more documentation about what the library actually contains. I know there is a HoTT book rosseta stone for finding theorems from there.

I would argue that Spaces is a terrible name for things that aren't really spaces. Truncations are used throughout HoTT non-stop and it is really sad that they are confined to HIT. Same goes for a lot of files in that folder. It seems a bit silly that we group all HIT together. A lot of these constructions are more fundmental rather than some special type we can create. Pushouts are defined as coequalisers, which is fine, but what are they doing in the HIT file? There are plenty of other files outside of HIT that use it.

Algebra only contains ooGroups and their friends but this is a pretty restricted view. This would be a place some the Math classes library could slip into. I am not a big fan of the classes library to be honest. If we want to talk about algebra from the HoTT point of view we should write from scratch.

Now that last one is a lot of work I know, so maybe we can start planning it now, and adding to it as we go along. And eventually get rid of the math classes and its dependence.

**Comment by mikeshulman** [comment]
Documentation is great: contributions are always welcome!

Maybe Spaces isn't a great name, but the files in that directory *are* about particular "spaces" (in the homotopy-theoretic sense).  We can't call it "Types" because we already have a "Types" directory that's about general properties of particular type *formers*.  Let us know if you have a better suggestion.

Truncations are not "confined" to HIT; other directories like Spaces are also allowed to use them.  They're excluded from Basics and Types mainly for reasons of dependency.  Pushouts and coequalizers are in the HIT directory because they *are* HITs, I'm not sure what your point is.

Also, this library is not only intended as a foundation to formalize mathematics in a-la UniMath, but also a context in which to investigate formal properties of HoTT, and in particular that means we need to keep track of dependencies.  When studying models that may or may not admit one kind of HIT or another, it's useful to see which parts of the theory depend on that HIT or don't.

The only reason Algebra contains only ooGroups is that no one has put anything else in it yet.  Keep in mind that there is no global dictator of the library saying "now X needs to be done; *you* go and do it!"  The library consists of what individual people have chosen to contribute to it, for whatever personal reasons they had at the time.

As for set-level algebra, I don't think there are any reasons to expect it to be noticeably different in HoTT from the way it looks in any other foundations, and the real problems in formalizing such things are bookkeeping rather than mathematical.  So I think it will save us a lot of work and needless confusion to use an existing library whose authors have thought carefully about how to organize a formalization of the profusion of structures in abstract algebra and made use of state-of-the-art tools like typeclass inference, and we're fortunate that @SkySkimmer has already ported the mathclasses library to HoTT.  If you feel like developing your own competing library of set-level algebra in a fork, no one will stop you, but my own opinion is that the HoTT library will be better served by not reinventing the wheel.

**Comment by spitters** [comment]
As we speak, @mattam82 and @andreaslyn are making progress on making Equations/Program work with the HoTT library. This would allow to port much more of the math-classes library.
Moreover, it would also allow agda style development in Coq.
https://github.com/HoTT/HoTT/issues/895
You are welcome to help resolving that issue.

For the rationale behind HoTT-classes; see @SkySkimmer 's paper. It was the easiest way to obtain a theory of real numbers.
