### ISSUE TITLE
Don't clobber & for sgop

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#976]
HoTT.Classes.interfaces.canonical_names defines `&` to mean `sgop`, which breaks the standard notation `{ x:A & P x }` for Sigma-types.  Let's find another symbol for `sgop`.

**Comment by Alizter** [comment]
Instead of `(*)` we have `(.*.)` since that would conflct with comments. Why not have `.&.`?

Other alternatives I can think of are `$`, `&&` but these may have their own problems.

**Comment by JasonGross** [comment]
If you put `&` at the right level (I don't know what level that is, but @herbelin probably does), then you might be able to get both infix `&` and the `{ x : A & P }` notations to play well together.

**Comment by herbelin** [comment]
> you might be able to get both infix & and the { x : A & P } notations to play well together.

Hi, that might not be so easy. In `{ x : A & P }`, `A` is parsed at level 200, i.e. at the higher level, which is the level of left-closed right-opened binders (`forall`, `fun`, ...).

Thus, if we have `{ x : A & B & P}` and don't want it to be parsed as `{ x : (A & B) & P}` (or worse, to be parsed at `{ x : ((A & B) & P)}` and possibly fail, depending on remaining context), one would need `A` to be parsed at a level lower than the one of `&`.

One could try to lower `A` to be at level 99 in the notation for `{ x : A & B & P}` which would then allow `&` to be at level 100 and still have `A` of the common form `A1 -> A2` (since `->` is at 99).

I tried for the standard library and this compiles (in particular I don't see notations of the form `{ x : forall ... & ... }` in the standard library).

One could actually move `A` even lower, e.g. to 20. Thanks to a tolerance of camlp5 which automatically raise levels when matching at the given level fails, one would still be able to parse say `{ x : nat * nat & P }` (as long as no infix notation is given on `&` yet). However, that would start to be complex. In particular, printing would insist in showing parentheses and adding a rule for `&` would break the tolerance of camlp5 I just mentioned.

So, at the end, using another notation than `&` might remain the simplest thing to do.

**Comment by mikeshulman** [comment]
Thanks @herbelin!  Given what you say (and the rareness of sgop), I agree that using another notation for sgop would be better.  I suspect there are plenty of `{ x : forall ... & ... }`s in the HoTT library, and even if there aren't yet I would want that to work if someone writes it.

**Comment by Alizter** [comment]
Could @ be a possibility?

**Comment by mikeshulman** [comment]
We use that for path concatenation...

**Comment by Alizter** [comment]
@mikeshulman If I understand the above discussion, the reason we can't get the two &'s to play nicely together is precisely because they have different levels. I would imagine any group operation ought to have the same level as path concatenation, so maybe there is a way to get them to play nice?

**Comment by mikeshulman** [comment]
I was worried about cognitive clashes rather than syntactic ones.

**Comment by Alizter** [comment]
What about `.`?

**Comment by mikeshulman** [comment]
That's always fraught because Coq also uses it as an end-of-command symbol.

**Comment by Alizter** [comment]
Perhaps we should have a discussion about using unicode. There is a historic discussion somewhere where it was agreed on keeping unicode a seperate matter. I am not suggesting we turn into the HoTT-agda library where every conceivable definition has a unicode notation, but a measured usage might be in order.

It doesn't really look likely we will find a better notation for the group operation. Although if we scope things well, we might be able to get away with `*`.

**Comment by mikeshulman** [comment]
It's always tempting, but I'd rather not open that can of worms.  What about something like `**` or `++`?

**Comment by Alizter** [comment]
Hmm, I’ll see if I can get `*` to work today.

**Comment by Alizter** [comment]
So in hottclasses we reserve `+` for anything that is an instance of Plus, `*` for anything that is an instance of Mult. One way to achieve what we want is to rewrite the data of a group to use Mult instead of SgOp. Since these are definitionally identical, it should cause no problems, and allow us to write `*`. What really needs to be done after this is disable the use of `&` in hottclasses unless we really want it. This could be achieved by putting `&` in a seperate scope (than mc_scope) that we locally open when we want to talk about semigroup like structures.

I thought it might make sense to get rid of SgOp completely and use Mult instead. This would mean all semigroup-like structures use `*` for their operation. I can't see any reason this might be undesirable?

We could also use Plus in the data of AbGroup so that we can write the operation with `+`. Though technically under the hood, `*` would equally work as a result. I have a feeling this might be very confusing. I haven't even considered how this might play out with ring-like structures.

**Comment by mikeshulman** [comment]
What is the difference between `Plus` and `Mult`?

**Comment by Alizter** [comment]
> What is the difference between `Plus` and `Mult`?

Only the notation that gets printed.

**Comment by mikeshulman** [comment]
Oh yikes.  I didn't realize hottclasses also did that bizarre thing.  Can we get rid of that duplication?  Mathematically a binary operation is a binary operation, regardless of what it's called.

**Comment by mikeshulman** [comment]
In a sensible world there would be one theory of "binary operations", and whoever wants to talk about a binary operation written with + could do that by (say) opening a particular notation scope, and whoever wants to write it with * could do that too, and they could all nevertheless use each other's theorems.

**Comment by Alizter** [comment]
Well they are all definitionally the same, so there is no issue using mult where a plus should go. The main issue I think was trying to be avoided is what happens when you have two binary operations. Then your notation scope doesn't work. Rings seem to make everything complicated here.

All Plus and Mult do is say I am a binary operation but I print a specific way.

**Comment by mikeshulman** [comment]
Ok, I see.  But they do a little more than that, because there is an instance `plus_is_sg_op` but not in reverse (otherwise there'd be loops).  So with the current structure I can't say "I want to prove things about an arbitrary semigroup and choose to write its operation additively" and use `Plus`, because then someone won't be able to apply my theorems to an arbitrary semigroup unless they also write it additively.

Would it work if in *addition* to `Plus` and `Mult`, we declared `*` and `+` as notations for `sg_op` in two different scopes (and got rid of `&`)?
