### ISSUE TITLE
How can we improve the library?

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#978]
What features do we want/need to make doing homotopy theory easier? It is very easy to get overwhelmed with matches and transports making it tricky to prove much about higher dimensional paths.

If you look at the [lean library](https://github.com/leanprover/lean2/blob/master/hott/cubical/square.hlean) there are many lemmas about squares. At the moment we have a few lemmas, namely whiskerings, in PathGroupoid.v. These would be useful things to add to this library. It would make some of the proofs in my pull request Hopf.v much easier too. You need only look at the lean implementation to see the benefits.

This has been in my opinion, one of the main obstacle to doing homotopy theory in the coq library. The Agda and lean implementations can deal with these constructions more naturally, thus they are written down faster.

Another thing is HIT. If we had more tactics like induction with support for HIT that would make writing some proofs easier. Especially with things like case analysis. (But this is a lot to ask for and I am not the only one asking).

It would be nice to hear what other people want for this library. What they think might help if it were implemented. Just so we are all aware on what people want. :-)

**Comment by mikeshulman** [comment]
The absence of lemmas about squares and cubes from this library is not a design choice, but an "early adopter problem" -- the basic structure of this library and its lemmas predates the [Licata-Brunerie paper](https://guillaumebrunerie.github.io/pdf/lb15cubicalsynth.pdf) that introduced the use of squares and cubes in Book HoTT.  That and the fact that no one has since been motivated to, and had the time to, implement them.  (The existing lemmas aren't too bad once you get used to them, but there are certainly applications for which squares and cubes are easier.)

A little while ago I started implementing some basic square and cube lemmas, but never polished them to the point of merging.  Since you seem to be interested in this, I went ahead and cleaned them up and made a PR #979.  If that seems like a good starting point, I think it would be great if you felt like adding to it with more lemmas and so on as in the agda and lean libraries.

**Comment by mikeshulman** [comment]
Regarding induction tactics, I've never really felt the lack of them for HITs.  Can you give an example of what you mean?  In general Coq's induction tactic is basically just "apply thing_ind" with some extra fanciness that guesses the induction motive, and I doubt the latter would be very useful or possible for HITs; usually I think it's better to carefully choose the induction motive by hand.

**Comment by Alizter** [comment]
When doing induction over a higher inductive type, I usually have to make an effort to turn transports into aps using `rewrite transport_paths_FlFr` or something. This almost always spews out silly terms like `bah @ 1` which I have to reduce later.

How can this behavior be improved and what is the best way to go about it?

If you want to see an example of what I mean see [these rewrites I have to do on pushouts](https://github.com/Alizter/HoTT/blob/4a896276592bf7725d6a3926cc34ce0707f7a14b/contrib/Imaginaroid.v#L77).

**Comment by mikeshulman** [comment]
Well, to start with you could use `transport_paths_FFlr` instead of `transport_paths_FlFr`, which seems more appropriate in this case.  You're not going to be able to get rid of the `concat_p1` since it's a `1` that you're transporting, unless we also created a dedicated lemma like `transport_paths_FFlr_1` for transporting identities; but then of course people would have to be aware of that lemma.  I'm just not really sure why you're bothered by stuff like this; it just seems to me like the fact of what homotopy theory is like: you have to do path algebra in order to reason about paths.

**Comment by Alizter** [comment]
I am closing this issue since its not very well defined anyway.
